import { Component, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { AuthService } from '../core/auth.service';

@Component({standalone:true,imports:[FormsModule,RouterLink],styles:[`.auth-page{min-height:100dvh;display:grid;place-items:center;background:radial-gradient(circle at top right,#25798a 0,#102f38 47%,#0a2229 100%);padding:32px 18px}.auth-card{width:min(100%,520px);padding:34px;border:0;border-radius:24px;box-shadow:0 24px 65px rgba(0,0,0,.26)}.brand{display:flex;align-items:center;gap:12px;margin-bottom:22px;font-size:.85rem;font-weight:900;letter-spacing:.13em;color:#168b9d}.brand img{width:58px;height:58px;object-fit:contain;background:#fff;border-radius:14px;padding:4px;box-shadow:0 5px 16px rgba(6,43,53,.12)}.brand span{display:grid;gap:4px}.brand small{font-size:.52rem;letter-spacing:.12em;color:#668188}.auth-card label{display:block;margin-bottom:6px;font-size:.9rem;font-weight:700}.auth-card .form-control{min-height:46px}.auth-card .alert{font-size:.9rem;overflow-wrap:anywhere}@media(max-width:575px){.auth-page{display:block;min-height:100dvh;padding:0;background:#f4f8f9}.auth-card{width:100%;min-height:100dvh;border-radius:0;padding:calc(24px + env(safe-area-inset-top)) 20px calc(34px + env(safe-area-inset-bottom));box-shadow:none}.auth-card h1{font-size:1.55rem}.auth-card .row{--bs-gutter-y:.75rem}.auth-card .btn{min-height:48px}.auth-card p{font-size:.94rem}}@media(max-height:650px) and (min-width:576px){.auth-page{place-items:start center;padding:16px}.auth-card{margin:auto 0}}`],template:`
<main class="auth-page"><section class="card auth-card"><div class="brand"><img src="/fima-auto-logo.jpg" alt="Logo FIMA AUTO"><span><small>LOCATION DE VÉHICULES</small>FIMA AUTO</span></div><h1 class="h3">{{register()?'Créer mon compte client':'Espace client'}}</h1><p class="text-muted">{{register()?'Créez votre accès pour réserver un véhicule en ligne.':'Connectez-vous pour suivre vos réservations et signer votre contrat.'}}</p>
@if(error()){<div class="alert alert-danger">{{error()}}</div>}@if(message()){<div class="alert alert-success">{{message()}}</div>}
@if(register()){<div class="row g-3"><div class="col-md-6"><label>Prénom <span class="required">*</span></label><input class="form-control" [(ngModel)]="firstName"></div><div class="col-md-6"><label>Nom <span class="required">*</span></label><input class="form-control" [(ngModel)]="lastName"></div><div class="col-12"><label>Téléphone <span class="required">*</span></label><input class="form-control" [(ngModel)]="phone"></div></div>}
<div class="mt-3"><label>E-mail <span class="required">*</span></label><input class="form-control" type="email" [(ngModel)]="email"></div><div class="mt-3"><label>Mot de passe <span class="required">*</span></label><input class="form-control" type="password" [(ngModel)]="password" autocomplete="current-password"></div><button class="btn btn-primary w-100 mt-4" [disabled]="loading()" (click)="submit()">{{loading()?'Traitement…':register()?'Créer mon compte':'Se connecter'}}</button><p class="text-center mt-3 mb-0">@if(register()){Déjà inscrit ? <a routerLink="/client/login">Se connecter</a>}@else{Nouveau client ? <a routerLink="/client/register">Créer un compte</a>}</p><p class="text-center mt-2 mb-0"><a routerLink="/login">Accès équipe interne</a></p></section></main>`})
export class ClientAuthComponent { register=signal(false); loading=signal(false); error=signal(''); message=signal(''); firstName='';lastName='';phone='';email='';password=''; constructor(private auth:AuthService,private router:Router){this.register.set(location.pathname.endsWith('/register'));}
 private authError(error: any){const message=this.auth.errorMessage(error);const code=String(error?.code??error?.status??'').trim();const raw=String(error?.message??'').trim();if(!message.startsWith('L’opération n’a pas pu'))return message;return code?'La création du compte a été refusée par Supabase (référence : '+code+').':raw?'La création du compte a été refusée par Supabase : '+raw+'.':'La création du compte a été refusée par Supabase. Réessayez après avoir rechargé la page.'}
 async submit(){this.error.set('');this.message.set('');if(!this.email.trim()||!this.password){this.error.set('Adresse e-mail et mot de passe obligatoires.');return}if(this.register()){if(!this.firstName.trim()||!this.lastName.trim()||!this.phone.trim()){this.error.set('Prénom, nom et téléphone obligatoires.');return}this.loading.set(true);const r=await this.auth.supabase().auth.signUp({email:this.email.trim(),password:this.password,options:{data:{full_name:(this.firstName+' '+this.lastName).trim(),first_name:this.firstName.trim(),last_name:this.lastName.trim(),phone:this.phone.trim()}}});this.loading.set(false);if(r.error){this.error.set(this.authError(r.error));return}if(r.data.session){await this.auth.load();const p=await this.auth.supabase().rpc('ensure_client_profile',{target_first_name:this.firstName,target_last_name:this.lastName,target_phone:this.phone,target_email:this.email});if(p.error){this.error.set(this.authError(p.error));return}await this.router.navigate(['/client/vehicles']);}else this.message.set('Compte créé. Vérifiez votre e-mail puis connectez-vous.');return}this.loading.set(true);const e=await this.auth.login(this.email.trim(),this.password);this.loading.set(false);if(e){this.error.set(this.authError(e));return}if(this.auth.profile()?.role!=='client'){await this.auth.logout();this.error.set('Ce compte appartient à l’équipe interne. Utilisez l’accès équipe.');return}await this.router.navigate(['/client/vehicles']);}}
