import { Component, OnInit, signal } from '@angular/core';
import { DatePipe, DecimalPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { AuthService } from '../core/auth.service';

@Component({
  standalone: true, imports: [FormsModule, DatePipe, DecimalPipe],
  template: `
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-0">Incidents</h1><small class="text-muted">Pannes, accidents, dommages et autres événements</small></div>@if (auth.can('incidents','create')) {<button class="btn btn-primary" (click)="openForm()">Nouvel incident</button>}</div>
    <div class="row g-2 mb-3"><div class="col-md-5"><input class="form-control" [(ngModel)]="search" (input)="filterRows()" placeholder="Rechercher"></div><div class="col-md-3"><select class="form-select" [(ngModel)]="statusFilter" (change)="filterRows()"><option value="">Tous statuts</option>@for (status of statuses; track status) {<option [value]="status">{{ status }}</option>}</select></div></div>
    @if (error()) {<div class="alert alert-danger">{{ error() }}</div>} @if (message()) {<div class="alert alert-success">{{ message() }}</div>} @if (loading()) {<p>Chargement…</p>} @if (!loading() && !filtered().length) {<div class="alert alert-light border">Aucun incident.</div>}
    @if (filtered().length) {<div class="table-responsive bg-white border rounded"><table class="table table-hover mb-0"><thead><tr><th>Date</th><th>Type</th><th>Véhicule</th><th>Client</th><th>Coût</th><th>Statut</th><th></th></tr></thead><tbody>@for (item of filtered(); track item.id) {<tr><td>{{ item.incident_date | date:'short' }}</td><td>{{ label(item.incident_type) }}</td><td>{{ item.vehicles?.registration_number || '—' }}</td><td>{{ item.clients?.first_name }} {{ item.clients?.last_name }}</td><td>{{ item.cost | number:'1.0-2' }}</td><td>{{ item.status }}</td><td><button class="btn btn-sm btn-outline-primary" (click)="edit(item)">Voir / modifier</button></td></tr>}</tbody></table></div>}
    @if (form()) {<section class="card mt-4"><div class="card-body"><h2 class="h5">{{ form()!.id ? 'Modifier' : 'Créer' }} un incident</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Type</label><select class="form-select" [(ngModel)]="form()!.incident_type"><option value="breakdown">Panne</option><option value="accident">Accident</option><option value="damage">Dommage</option><option value="infraction">Infraction</option><option value="delay">Retard</option><option value="other">Autre</option></select></div><div class="col-md-4"><label class="form-label">Date / heure</label><input class="form-control" type="datetime-local" [(ngModel)]="form()!.incident_date"></div><div class="col-md-4"><label class="form-label">Statut</label><select class="form-select" [(ngModel)]="form()!.status"><option value="open">Ouvert</option><option value="in_progress">En cours</option><option value="resolved">Résolu</option><option value="closed">Clôturé</option></select></div><div class="col-md-4"><label class="form-label">Véhicule</label><select class="form-select" [(ngModel)]="form()!.vehicle_id"><option value="">Aucun</option>@for (vehicle of vehicles(); track vehicle.id) {<option [value]="vehicle.id">{{ vehicle.registration_number }}</option>}</select></div><div class="col-md-4"><label class="form-label">Location associée</label><select class="form-select" [(ngModel)]="form()!.rental_id"><option value="">Aucune</option>@for (rental of rentals(); track rental.id) {<option [value]="rental.id">{{ rental.vehicles?.registration_number }} — {{ rental.clients?.first_name }} {{ rental.clients?.last_name }}</option>}</select></div><div class="col-md-4"><label class="form-label">Client associé</label><select class="form-select" [(ngModel)]="form()!.client_id"><option value="">Aucun</option>@for (client of clients(); track client.id) {<option [value]="client.id">{{ client.first_name }} {{ client.last_name }}</option>}</select></div><div class="col-md-4"><label class="form-label">Coût</label><input class="form-control" type="number" min="0" step="0.01" [(ngModel)]="form()!.cost"></div><div class="col-md-8"><label class="form-label">Photos / documents</label><input class="form-control" type="file" multiple accept="application/pdf,image/png,image/jpeg,image/webp" (change)="chooseFiles($event)"><small class="text-muted">Stockage privé si la permission Documents est également attribuée.</small></div><div class="col-12"><label class="form-label">Description</label><textarea class="form-control" rows="3" [(ngModel)]="form()!.description"></textarea></div></div><button class="btn btn-success mt-3" [disabled]="saving()" (click)="save()">{{ saving() ? 'Enregistrement…' : 'Enregistrer' }}</button><button class="btn btn-link mt-3" (click)="form.set(null)">Annuler</button></div></section>}
  `
})
export class IncidentsComponent implements OnInit {
  rows = signal<any[]>([]); filtered = signal<any[]>([]); vehicles = signal<any[]>([]); rentals = signal<any[]>([]); clients = signal<any[]>([]); form = signal<any>(null); loading = signal(false); saving = signal(false); error = signal(''); message = signal(''); search = ''; statusFilter = ''; statuses = ['open','in_progress','resolved','closed']; private files: File[] = [];
  constructor(public auth: AuthService, private route: ActivatedRoute) {}
  async ngOnInit() { await this.load(); const vehicle = this.route.snapshot.queryParamMap.get('vehicle'); const rental = this.route.snapshot.queryParamMap.get('rental'); if ((vehicle || rental) && this.auth.can('incidents','create')) await this.openForm(vehicle ?? '', rental ?? ''); }
  private fail(value: unknown) { this.error.set(this.auth.errorMessage(value)); this.message.set(''); }
  async load() { this.loading.set(true); const result = await this.auth.supabase().from('incidents').select('*,vehicles(registration_number),clients(first_name,last_name)').order('incident_date',{ascending:false}); this.loading.set(false); if (result.error) return this.fail(result.error); this.rows.set(result.data ?? []); this.filterRows(); }
  filterRows() { const term = this.search.toLowerCase(); this.filtered.set(this.rows().filter(item => (!this.statusFilter || item.status === this.statusFilter) && (!term || `${item.description} ${item.vehicles?.registration_number ?? ''} ${item.clients?.first_name ?? ''} ${item.clients?.last_name ?? ''}`.toLowerCase().includes(term)))); }
  async openForm(vehicleId = '', rentalId = '') { const [vehicles, rentals, clients] = await Promise.all([this.auth.supabase().from('vehicles').select('id,registration_number').order('registration_number'),this.auth.supabase().from('rentals').select('id,vehicle_id,client_id,vehicles(registration_number),clients(first_name,last_name)').order('created_at',{ascending:false}),this.auth.supabase().from('clients').select('id,first_name,last_name').order('last_name')]); const failure = vehicles.error ?? rentals.error ?? clients.error; if (failure) return this.fail(failure); this.vehicles.set(vehicles.data ?? []); this.rentals.set(rentals.data ?? []); this.clients.set(clients.data ?? []); this.files=[]; this.form.set({ vehicle_id: vehicleId || null, rental_id: rentalId || null, client_id: null, incident_type:'breakdown',description:'',incident_date:this.localDateTime(),cost:0,status:'open' }); }
  async edit(value: any) { if (!this.auth.can('incidents','update')) return; await this.openForm(); this.form.set({ ...value, incident_date: new Date(value.incident_date).toISOString().slice(0,16) }); }
  chooseFiles(event: Event) { this.files = Array.from((event.target as HTMLInputElement).files ?? []); }
  label(type: string) { return ({breakdown:'Panne',accident:'Accident',damage:'Dommage',infraction:'Infraction',delay:'Retard',other:'Autre'} as Record<string,string>)[type] ?? type; }
  async save() { const form = this.form(); if (!form?.description?.trim() || Number(form.cost) < 0) return this.fail('Description et coût valide sont requis.'); this.saving.set(true); const payload={...form,incident_date:new Date(form.incident_date).toISOString()}; const result=form.id?await this.auth.supabase().from('incidents').update(payload).eq('id',form.id).select().single():await this.auth.supabase().from('incidents').insert(payload).select().single(); if(result.error){this.saving.set(false);return this.fail(result.error);} for(const file of this.files){const path=`incidents/${result.data.id}/${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const uploaded=await this.auth.supabase().storage.from('rental-documents').upload(path,file,{upsert:false});if(uploaded.error){this.saving.set(false);return this.fail(`Incident enregistré, mais document non envoyé : ${this.auth.errorMessage(uploaded.error)}`);}const document=await this.auth.supabase().from('incident_documents').insert({incident_id:result.data.id,document_name:file.name,storage_path:path,mime_type:file.type});if(document.error){this.saving.set(false);return this.fail(`Document non référencé : ${this.auth.errorMessage(document.error)}`);}}this.saving.set(false);this.form.set(null);this.message.set('Incident enregistré.');await this.load();}
  private localDateTime(){const now=new Date();now.setMinutes(now.getMinutes()-now.getTimezoneOffset());return now.toISOString().slice(0,16);}
}


