import { Component, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { AuthService } from '../core/auth.service';

type PhotoType = 'front' | 'rear' | 'left_side' | 'right_side' | 'interior';
const photoTypes: { key: PhotoType; label: string }[] = [
  { key: 'front', label: 'Avant' }, { key: 'rear', label: 'Arrière' }, { key: 'left_side', label: 'Côté gauche' }, { key: 'right_side', label: 'Côté droit' }, { key: 'interior', label: 'Intérieur' }
];

@Component({
  standalone: true,
  imports: [FormsModule, DatePipe],
  template: `
    <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><h1 class="h3 mb-0">Inspections</h1><small class="text-muted">États des lieux de départ et de retour</small></div>@if (auth.can('inspections', 'create')) {<button class="btn btn-primary" (click)="openForm()">Nouvelle inspection</button>}</div>
    @if (error()) {<div class="alert alert-danger">{{ error() }}</div>} @if (message()) {<div class="alert alert-success">{{ message() }}</div>} @if (loading()) {<p class="text-muted">Chargement…</p>}
    @if (!loading() && !inspections().length) {<div class="alert alert-light border">Aucune inspection enregistrée.</div>}
    @if (inspections().length) {<div class="table-responsive bg-white border rounded"><table class="table table-hover mb-0"><thead><tr><th>Type</th><th>Client</th><th>Véhicule</th><th>Date</th><th>Kilométrage</th><th>Carburant</th><th></th></tr></thead><tbody>@for (item of inspections(); track item.id) {<tr><td>{{ item.inspection_type === 'departure' ? 'Départ' : 'Retour' }}</td><td>{{ item.rentals?.clients?.first_name }} {{ item.rentals?.clients?.last_name }}</td><td>{{ item.rentals?.vehicles?.registration_number }}</td><td>{{ item.inspection_date | date:'short' }}</td><td>{{ item.mileage }}</td><td>{{ item.fuel_level || '—' }}</td><td><button class="btn btn-sm btn-outline-primary" (click)="showRental(item.rental_id)">Comparer</button></td></tr>}</tbody></table></div>}
    @if (form()) {<section class="card mt-4"><div class="card-body"><h2 class="h5">Inspection {{ form()!.inspection_type === 'departure' ? 'de départ' : 'de retour' }}</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Location</label><select class="form-select" [(ngModel)]="form()!.rental_id" (change)="selectRental()"><option value="">Sélectionner une location</option>@for (rental of rentals(); track rental.id) {<option [value]="rental.id">{{ rental.clients?.first_name }} {{ rental.clients?.last_name }} — {{ rental.vehicles?.registration_number }} ({{ rental.status }})</option>}</select></div><div class="col-md-3"><label class="form-label">Type</label><select class="form-select" [(ngModel)]="form()!.inspection_type"><option value="departure">Départ</option><option value="return">Retour</option></select></div><div class="col-md-3"><label class="form-label">Date / heure</label><input class="form-control" type="datetime-local" [(ngModel)]="form()!.inspection_date"></div><div class="col-md-4"><label class="form-label">Kilométrage</label><input class="form-control" min="0" type="number" [(ngModel)]="form()!.mileage"></div><div class="col-md-4"><label class="form-label">Niveau de carburant</label><input class="form-control" [(ngModel)]="form()!.fuel_level" placeholder="Ex. plein, 1/2"></div><div class="col-md-4"><label class="form-label">Dommages constatés</label><input class="form-control" [(ngModel)]="form()!.damagesText" placeholder="Un dommage par ligne"></div><div class="col-12"><label class="form-label">Observations</label><textarea class="form-control" rows="3" [(ngModel)]="form()!.observations"></textarea></div></div>
      <h3 class="h6 mt-4">Photos (facultatives)</h3><div class="row g-3">@for (type of photoTypes; track type.key) {<div class="col-md"><label class="form-label">{{ type.label }}</label><input class="form-control" type="file" accept="image/png,image/jpeg,image/webp" (change)="choosePhoto(type.key, $event)"></div>}</div>
      <button class="btn btn-success mt-4" [disabled]="saving()" (click)="save()">{{ saving() ? 'Enregistrement…' : 'Enregistrer l’inspection' }}</button><button class="btn btn-link mt-4" (click)="form.set(null)">Annuler</button>
    </div></section>}
    @if (comparison()) {<section class="card mt-4"><div class="card-body"><div class="d-flex justify-content-between"><h2 class="h5">Comparaison départ / retour</h2><button class="btn-close" (click)="comparison.set(null)"></button></div>@if (!comparison().departure) {<p class="text-muted">Inspection de départ absente.</p>} @if (!comparison().return) {<p class="text-muted">Inspection de retour absente.</p>} @if (comparison().departure && comparison().return) {<div class="table-responsive"><table class="table"><thead><tr><th>Élément</th><th>Départ</th><th>Retour</th><th>Différence</th></tr></thead><tbody><tr><td>Kilométrage</td><td>{{ comparison().departure.mileage }}</td><td>{{ comparison().return.mileage }}</td><td>{{ comparison().return.mileage - comparison().departure.mileage }} km</td></tr><tr><td>Carburant</td><td>{{ comparison().departure.fuel_level || '—' }}</td><td>{{ comparison().return.fuel_level || '—' }}</td><td>{{ comparison().departure.fuel_level === comparison().return.fuel_level ? 'Identique' : 'Modifié' }}</td></tr><tr><td>Dommages</td><td>{{ damagesText(comparison().departure) }}</td><td>{{ damagesText(comparison().return) }}</td><td>{{ damagesText(comparison().departure) === damagesText(comparison().return) ? 'Identiques' : 'À vérifier' }}</td></tr><tr><td>Observations</td><td>{{ comparison().departure.observations || '—' }}</td><td>{{ comparison().return.observations || '—' }}</td><td>{{ comparison().departure.observations === comparison().return.observations ? 'Identiques' : 'À vérifier' }}</td></tr></tbody></table></div>}</div></section>}
  `
})
export class InspectionsComponent implements OnInit {
  photoTypes = photoTypes; inspections = signal<any[]>([]); rentals = signal<any[]>([]); form = signal<any>(null); comparison = signal<any>(null); loading = signal(false); saving = signal(false); error = signal(''); message = signal('');
  private photos = new Map<PhotoType, File>();
  constructor(public auth: AuthService, private route: ActivatedRoute) {}
  async ngOnInit() { await this.load(); const rentalId = this.route.snapshot.queryParamMap.get('rental'); if (rentalId && this.auth.can('inspections', 'create')) await this.openForm(rentalId); }
  private fail(error: unknown) { this.error.set(error instanceof Error ? error.message : String(error)); this.message.set(''); }
  private clear() { this.error.set(''); this.message.set(''); }
  async load() { this.loading.set(true); const result = await this.auth.supabase().from('vehicle_inspections').select('*,rentals(id,clients(first_name,last_name),vehicles(registration_number))').order('inspection_date', { ascending: false }); this.loading.set(false); if (result.error) return this.fail(result.error.message); this.inspections.set(result.data ?? []); }
  async openForm(preselectedRentalId = '') { this.clear(); this.photos.clear(); await this.auth.supabase().rpc('refresh_overdue_rentals'); const result = await this.auth.supabase().from('rentals').select('id,status,vehicle_id,clients(first_name,last_name),vehicles(registration_number)').in('status', ['pending', 'active', 'overdue']); if (result.error) return this.fail(this.auth.errorMessage(result.error)); this.rentals.set(result.data ?? []); this.form.set({ rental_id: preselectedRentalId, vehicle_id: '', inspection_type: 'departure', inspection_date: this.localDateTime(), mileage: 0, fuel_level: '', damagesText: '', observations: '' }); this.selectRental(); }
  selectRental() { const form = this.form(); const rental = this.rentals().find(item => item.id === form?.rental_id); if (rental) this.form.set({ ...form, vehicle_id: rental.vehicle_id }); }
  choosePhoto(type: PhotoType, event: Event) { const file = (event.target as HTMLInputElement).files?.[0]; if (file) this.photos.set(type, file); }
  async save() {
    this.clear(); const form = this.form(); if (!form?.rental_id || !form.vehicle_id || Number(form.mileage) < 0) return this.fail('Location, véhicule et kilométrage valide sont requis.');
    this.saving.set(true); const inspection = await this.auth.supabase().from('vehicle_inspections').insert({ rental_id: form.rental_id, vehicle_id: form.vehicle_id, inspection_type: form.inspection_type, inspection_date: new Date(form.inspection_date).toISOString(), mileage: Number(form.mileage), fuel_level: form.fuel_level || null, observations: form.observations || null, damages: form.damagesText ? form.damagesText.split('\n').map((item: string) => item.trim()).filter(Boolean) : [] }).select().single();
    if (inspection.error) { this.saving.set(false); return this.fail(inspection.error.message); }
    for (const [type, file] of this.photos) { const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, '_'); const path = `inspections/${inspection.data.id}/${type}-${safeName}`; const upload = await this.auth.supabase().storage.from('inspection-photos').upload(path, file, { upsert: false }); if (upload.error) { this.saving.set(false); return this.fail(`Inspection créée, mais photo ${type} non envoyée : ${upload.error.message}`); } const photo = await this.auth.supabase().from('inspection_photos').insert({ inspection_id: inspection.data.id, photo_type: type, storage_path: path }); if (photo.error) { this.saving.set(false); return this.fail(`Inspection créée, mais référence photo ${type} non enregistrée : ${photo.error.message}`); } }
    this.saving.set(false); this.form.set(null); this.photos.clear(); this.message.set('Inspection et photos enregistrées.'); await this.load(); await this.showRental(inspection.data.rental_id);
  }
  async showRental(rentalId: string) { this.clear(); const result = await this.auth.supabase().from('vehicle_inspections').select('*').eq('rental_id', rentalId); if (result.error) return this.fail(result.error.message); this.comparison.set({ departure: result.data?.find(item => item.inspection_type === 'departure'), return: result.data?.find(item => item.inspection_type === 'return') }); }
  damagesText(item: any): string { return Array.isArray(item?.damages) && item.damages.length ? item.damages.join('; ') : 'Aucun'; }
  private localDateTime(): string { const now = new Date(); now.setMinutes(now.getMinutes() - now.getTimezoneOffset()); return now.toISOString().slice(0, 16); }
}
