import { Component, OnInit, signal } from '@angular/core';
import { DatePipe, DecimalPipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute } from '@angular/router';
import { AuthService } from '../core/auth.service';

@Component({
  standalone: true, imports: [FormsModule, DatePipe, DecimalPipe],
  template: `
    <div class="d-flex justify-content-between align-items-center mb-3"><div><h1 class="h3 mb-0">Maintenance</h1><small class="text-muted">Suivi et échéances des véhicules</small></div>@if (auth.can('maintenance','create')) {<button class="btn btn-primary" (click)="openForm()">Nouvelle maintenance</button>}</div>
    @if (error()) {<div class="alert alert-danger">{{ error() }}</div>} @if (message()) {<div class="alert alert-success">{{ message() }}</div>} @if (loading()) {<p>Chargement…</p>} @if (!loading() && !rows().length) {<div class="alert alert-light border">Aucune maintenance enregistrée.</div>}
    @if (rows().length) {<div class="table-responsive bg-white border rounded"><table class="table table-hover mb-0"><thead><tr><th>Véhicule</th><th>Type</th><th>Dernière</th><th>Prochaine</th><th>Coût</th><th>Statut</th><th></th></tr></thead><tbody>@for (item of rows(); track item.id) {<tr [class.table-warning]="due(item)"><td>{{ item.vehicles?.registration_number }}</td><td>{{ item.maintenance_type }}</td><td>{{ item.maintenance_date | date }}</td><td>{{ item.next_maintenance_date | date }}</td><td>{{ item.cost | number:'1.0-2' }}</td><td>{{ item.status }}</td><td><button class="btn btn-sm btn-outline-primary" (click)="edit(item)">Voir / modifier</button></td></tr>}</tbody></table></div>}
    @if (form()) {<section class="card mt-4"><div class="card-body"><h2 class="h5">{{ form()!.id ? 'Modifier' : 'Créer' }} une maintenance</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Véhicule</label><select class="form-select" [(ngModel)]="form()!.vehicle_id"><option value="">Sélectionner</option>@for (vehicle of vehicles(); track vehicle.id) {<option [value]="vehicle.id">{{ vehicle.registration_number }} — {{ vehicle.make }} {{ vehicle.model }}</option>}</select></div><div class="col-md-6"><label class="form-label">Type</label><input class="form-control" [(ngModel)]="form()!.maintenance_type" placeholder="Révision, pneus, vidange…"></div><div class="col-md-4"><label class="form-label">Date dernière maintenance</label><input class="form-control" type="date" [(ngModel)]="form()!.maintenance_date"></div><div class="col-md-4"><label class="form-label">Prochaine maintenance</label><input class="form-control" type="date" [(ngModel)]="form()!.next_maintenance_date"></div><div class="col-md-4"><label class="form-label">Kilométrage</label><input class="form-control" min="0" type="number" [(ngModel)]="form()!.mileage"></div><div class="col-md-4"><label class="form-label">Coût</label><input class="form-control" min="0" type="number" step="0.01" [(ngModel)]="form()!.cost"></div><div class="col-md-4"><label class="form-label">Garage / prestataire</label><input class="form-control" [(ngModel)]="form()!.provider_name"></div><div class="col-md-4"><label class="form-label">Statut</label><select class="form-select" [(ngModel)]="form()!.status"><option value="planned">Planifiée</option><option value="in_progress">En cours</option><option value="completed">Terminée</option><option value="cancelled">Annulée</option></select></div><div class="col-md-6"><label class="form-label">Facture / document</label><input class="form-control" type="file" accept="application/pdf,image/png,image/jpeg,image/webp" (change)="chooseFile($event)"><small class="text-muted">Stockage privé si vous disposez aussi de la permission Documents.</small></div><div class="col-12"><label class="form-label">Notes</label><textarea class="form-control" [(ngModel)]="form()!.description"></textarea></div></div><button class="btn btn-success mt-3" [disabled]="saving()" (click)="save()">{{ saving() ? 'Enregistrement…' : 'Enregistrer' }}</button><button class="btn btn-link mt-3" (click)="form.set(null)">Annuler</button></div></section>}
  `
})
export class MaintenanceComponent implements OnInit {
  rows = signal<any[]>([]); vehicles = signal<any[]>([]); form = signal<any>(null); loading = signal(false); saving = signal(false); error = signal(''); message = signal(''); private file?: File;
  constructor(public auth: AuthService, private route: ActivatedRoute) {}
  async ngOnInit() { await this.load(); const vehicle = this.route.snapshot.queryParamMap.get('vehicle'); if (vehicle && this.auth.can('maintenance','create')) await this.openForm(vehicle); }
  private fail(value: unknown) { this.error.set(value instanceof Error ? value.message : String(value)); this.message.set(''); }
  async load() { this.loading.set(true); const result = await this.auth.supabase().from('vehicle_maintenance').select('*,vehicles(registration_number,make,model)').order('maintenance_date',{ascending:false}); this.loading.set(false); if (result.error) return this.fail(result.error.message); this.rows.set(result.data ?? []); }
  async openForm(vehicleId = '') { const result = await this.auth.supabase().from('vehicles').select('id,registration_number,make,model').order('registration_number'); if (result.error) return this.fail(result.error.message); this.vehicles.set(result.data ?? []); this.file = undefined; this.form.set({ vehicle_id: vehicleId, maintenance_type: '', maintenance_date: new Date().toISOString().slice(0,10), next_maintenance_date: null, mileage: null, cost: 0, provider_name: '', description: '', status: 'planned' }); }
  async edit(value: any) { if (!this.auth.can('maintenance','update')) return; await this.openForm(); this.form.set({ ...value, maintenance_date: value.maintenance_date?.slice(0,10), next_maintenance_date: value.next_maintenance_date?.slice(0,10) }); }
  chooseFile(event: Event) { this.file = (event.target as HTMLInputElement).files?.[0]; }
  due(value: any) { return value.status !== 'completed' && value.next_maintenance_date && new Date(value.next_maintenance_date) <= new Date(Date.now() + 30 * 86400000); }
  async save() { const form = this.form(); if (!form?.vehicle_id || !form.maintenance_type || !form.maintenance_date || Number(form.cost) < 0) return this.fail('Véhicule, type, date et coût valide sont requis.'); this.saving.set(true); const payload = { ...form }; delete payload.vehicles; const result = form.id ? await this.auth.supabase().from('vehicle_maintenance').update(payload).eq('id',form.id).select().single() : await this.auth.supabase().from('vehicle_maintenance').insert(payload).select().single(); if (result.error) { this.saving.set(false); return this.fail(result.error.message); } if (this.file) { const path = `maintenance/${result.data.id}/${this.file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`; const upload = await this.auth.supabase().storage.from('rental-documents').upload(path,this.file,{upsert:false}); if (upload.error) { this.saving.set(false); return this.fail(`Maintenance enregistrée, mais facture non envoyée : ${upload.error.message}`); } const updated = await this.auth.supabase().from('vehicle_maintenance').update({invoice_storage_path:path}).eq('id',result.data.id); if (updated.error) { this.saving.set(false); return this.fail(updated.error.message); } } this.saving.set(false); this.form.set(null); this.message.set('Maintenance enregistrée.'); await this.load(); }
}
