import { Component, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../core/auth.service';
import { ActorNamesService } from '../core/actor-names.service';

@Component({
  standalone:true,
  imports:[FormsModule,DatePipe],
  styles:[`
    .amount{font-weight:750;white-space:nowrap}.invoice{max-width:860px;margin:1.5rem auto;background:#fff;border:1px solid #dce8ea;border-radius:16px;overflow:hidden}.invoice-head{padding:26px 30px;background:linear-gradient(120deg,#f8fcfc,#e7f4f6);border-bottom:4px solid #1593a5}.invoice-head h2{margin:0;color:#12313a}.invoice-body{padding:28px 30px}.invoice-total{padding:14px 16px;background:#f4fafb;border-left:4px solid #1593a5}.caution{margin-top:18px;padding:14px 16px;border:1px dashed #91b7bd;border-radius:10px;background:#fcfefe}@media print{body *{visibility:hidden!important}.invoice,.invoice *{visibility:visible!important}.invoice{position:absolute;inset:0;max-width:none;border:0;border-radius:0}.no-print{display:none!important}}
  `],
  template:`
    <div class="page-heading no-print"><div><p class="eyebrow">SUIVI FINANCIER</p><h1>Paiements</h1><p>Historique des encaissements physiques confirmés depuis les locations.</p></div></div>
    @if(error()){<div class="alert alert-danger no-print">{{error()}}</div>}@if(loading()){<div class="empty-state no-print">Chargement de l’historique…</div>}
    @if(!loading()&&!rows().length){<div class="empty-state no-print">Aucune location à afficher.</div>}
    @if(rows().length){<div class="table-responsive app-table no-print"><table class="table align-middle mb-0"><thead><tr><th>Client</th><th>Location / véhicule</th><th>Total</th><th>Montant reçu</th><th>Solde</th><th>Statut</th><th>Caution</th><th></th></tr></thead><tbody>@for(row of rows();track row.id){<tr><td><strong>{{row.clients?.first_name}} {{row.clients?.last_name}}</strong><br><small class="text-muted">{{row.clients?.phone||'—'}}</small></td><td><strong>{{row.vehicles?.registration_number||'—'}}</strong><br><small class="text-muted">{{row.vehicles?.make||''}} {{row.vehicles?.model||''}}</small></td><td class="amount">{{money(row.rental_price)}}</td><td class="amount">{{money(received(row))}}</td><td class="amount">{{money(outstanding(row))}}</td><td><span class="badge text-bg-{{tone(row)}}">{{paymentStatus(row)}}</span></td><td class="amount">{{money(row.deposit_amount)}}</td><td><button class="btn btn-sm btn-outline-primary" (click)="detail(row)">Détail</button></td></tr>}</tbody></table></div>}
    @if(selected()){<article class="invoice"><header class="invoice-head"><div class="d-flex justify-content-between gap-3"><div><p class="eyebrow mb-1">JUSTIFICATIF D’ENCAISSEMENT</p><h2>Situation financière de la location</h2></div><div class="text-end"><small>Édité le</small><br><strong>{{today|date:'medium'}}</strong></div></div></header><div class="invoice-body"><div class="row g-3 mb-4"><div class="col-md-6"><h3 class="h6 text-uppercase text-muted">Client</h3><strong>{{selected().clients?.first_name}} {{selected().clients?.last_name}}</strong><br>{{selected().clients?.phone||'Téléphone non renseigné'}}<br>{{selected().clients?.email||''}}</div><div class="col-md-6"><h3 class="h6 text-uppercase text-muted">Location</h3><strong>{{selected().vehicles?.registration_number||'Véhicule'}}</strong> — {{selected().vehicles?.make||''}} {{selected().vehicles?.model||''}}<br>Départ : {{selected().departure_date|date:'medium'}}<br>Retour prévu : {{selected().return_date|date:'medium'}}</div></div><div class="row g-3 text-center"><div class="col-md-4"><div class="invoice-total"><small>Prix total</small><strong class="d-block fs-5">{{money(selected().rental_price)}}</strong></div></div><div class="col-md-4"><div class="invoice-total"><small>Montant reçu</small><strong class="d-block fs-5 text-success">{{money(received(selected()))}}</strong></div></div><div class="col-md-4"><div class="invoice-total"><small>Solde restant</small><strong class="d-block fs-5">{{money(outstanding(selected()))}}</strong></div></div></div><div class="d-flex justify-content-between align-items-center mt-4"><h3 class="h6 mb-0">Historique des paiements</h3><span class="badge text-bg-{{tone(selected())}}">{{paymentStatus(selected())}}</span></div>@if(!selectedPayments().length){<p class="text-muted mt-3">Aucun paiement reçu pour cette location.</p>}@else{<div class="table-responsive mt-2"><table class="table table-sm"><thead><tr><th>Date</th><th>Montant</th><th>Moyen</th><th>Référence / observation</th><th>Confirmé par</th></tr></thead><tbody>@for(payment of selectedPayments();track payment.id){<tr><td>{{payment.payment_date|date:'short'}}</td><td class="amount">{{money(payment.amount)}}</td><td>{{method(payment.payment_method)}}</td><td>{{payment.reference||'—'}}@if(payment.observation){ — {{payment.observation}}}</td><td>{{actorName(payment.recorded_by)}}</td></tr>}</tbody></table></div>}<div class="caution"><div class="d-flex justify-content-between"><strong>Caution</strong><strong>{{money(selected().deposit_amount)}}</strong></div><small class="text-muted">Montant prévu lors de la location. Il est affiché à titre d’information et n’entre pas dans le chiffre d’affaires.</small></div><div class="mt-4 d-flex gap-2 no-print"><button class="btn btn-primary" (click)="print()">Imprimer le justificatif</button><button class="btn btn-outline-secondary" (click)="selected.set(null)">Fermer</button></div></div></article>}
  `
})
export class PaymentsComponent implements OnInit{
  rows=signal<any[]>([]);selected=signal<any>(null);selectedPayments=signal<any[]>([]);loading=signal(false);error=signal('');today=new Date();
  constructor(public auth:AuthService,private actors:ActorNamesService){}
  async ngOnInit(){await this.load()}
  async load(){this.loading.set(true);this.error.set('');const [rentals,payments]=await Promise.all([this.auth.supabase().from('rentals').select('*,clients(first_name,last_name,phone,email),vehicles(registration_number,make,model)').order('created_at',{ascending:false}),this.auth.supabase().from('payments').select('*').order('payment_date',{ascending:false})]);this.loading.set(false);if(rentals.error||payments.error){this.error.set(this.auth.errorMessage(rentals.error??payments.error));return}const byRental=new Map<string,any[]>();for(const payment of payments.data??[]){const current=byRental.get(payment.rental_id)??[];current.push(payment);byRental.set(payment.rental_id,current)}const prepared=(rentals.data??[]).map(rental=>({...rental,payments:byRental.get(rental.id)??[]}));this.rows.set(prepared);await this.actors.load((payments.data??[]).map(payment=>payment.recorded_by))}
  actorName(id:string|null|undefined){return this.actors.label(id)}
  received(row:any){return(row?.payments??[]).reduce((sum:number,payment:any)=>sum+Number(payment.amount??0),0)}outstanding(row:any){return Math.max(0,Number(row?.rental_price??0)-this.received(row))}paymentStatus(row:any){const total=Number(row?.rental_price??0),received=this.received(row);return received<=0?'Non payé':received<total?'Partiellement payé':'Payé'}tone(row:any){return this.paymentStatus(row)==='Payé'?'success':this.paymentStatus(row)==='Partiellement payé'?'warning':'secondary'}money(value:any){return Number(value??0).toLocaleString('fr-FR')+' FCFA'}method(value:string){return({cash:'Espèces',bank_transfer:'Virement',mobile_money:'Mobile money',other:'Autre'}as Record<string,string>)[value]??'—'}
  detail(row:any){this.error.set('');this.selected.set(row);this.selectedPayments.set(row.payments??[])}print(){window.print()}
}


