import { Component, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { ActorNamesService } from '../core/actor-names.service';

@Component({
  standalone:true,
  imports:[FormsModule,DatePipe,RouterLink],
  styles:[`
    .wizard-progress{display:flex;gap:8px;margin-bottom:24px}.wizard-step{flex:1;padding:10px;border-radius:10px;background:#edf2f3;color:#71858b;text-align:center;font-weight:700;font-size:.85rem}.wizard-step.active{background:#0b9cac;color:#fff}.document-upload{padding:14px;border:1px dashed #78b8c1;border-radius:12px;background:#f5fbfc}.detail-docs{display:flex;flex-wrap:wrap;gap:8px}
  `],
  template:`
  <div class="page-heading"><div><p class="eyebrow">EXPLOITATION</p><h1>Locations</h1><p>Créez une location avec le client, ses pièces, le véhicule et le paiement physique.</p></div>@if(auth.can('rentals','create')){<button class="btn btn-primary" (click)="openNew()">+ Nouvelle location</button>}</div>
  <div class="toolbar row g-2"><div class="col-md-7"><input class="form-control" [(ngModel)]="search" (input)="load()" placeholder="Client ou véhicule"></div><div class="col-md-5"><select class="form-select" [(ngModel)]="filter" (change)="load()"><option value="">Tous les statuts</option>@for(status of statuses;track status){<option [value]="status">{{statusLabel(status)}}</option>}</select></div></div>
  @if(error()){<div class="alert alert-danger">{{error()}}</div>}@if(message()){<div class="alert alert-success">{{message()}}</div>}@if(loading()){<div class="empty-state">Chargement des locations…</div>}@else if(!rows().length){<div class="empty-state">Aucune location.</div>}@else{<div class="table-responsive app-table"><table class="table align-middle mb-0"><thead><tr><th>Client</th><th>Véhicule</th><th>Départ</th><th>Statut</th><th>Paiement</th><th></th></tr></thead><tbody>@for(rental of rows();track rental.id){<tr><td><strong>{{rental.clients?.first_name}} {{rental.clients?.last_name}}</strong><small class="d-block text-muted">{{rental.clients?.phone}}</small></td><td>{{rental.vehicles?.registration_number}}</td><td>{{rental.departure_date|date:'short'}}</td><td><span class="badge text-bg-{{statusTone(rental.status)}}">{{statusLabel(rental.status)}}</span></td><td><span class="badge text-bg-{{rental.payment_received?'success':'secondary'}}">{{rental.payment_received?'Reçu':'Non reçu'}}</span></td><td><button class="btn btn-sm btn-outline-primary" (click)="detail(rental)">Fiche</button></td></tr>}</tbody></table></div>}
  @if(wizard()){<section class="card form-card mt-4"><div class="card-body"><div class="d-flex justify-content-between gap-3 align-items-start"><div><h2 class="h4">{{editingId()?'Modifier la location':'Nouvelle location'}}</h2><p class="text-muted mb-0">Les champs marqués <span class="required">*</span> sont obligatoires.</p></div><button class="btn-close" (click)="closeWizard()"></button></div><div class="wizard-progress mt-4"><div class="wizard-step" [class.active]="step()===1">1. Informations client</div><div class="wizard-step" [class.active]="step()===2">2. Informations location</div></div>
  @if(step()===1){<div class="row g-3"><div class="col-md-4"><label>Prénom <span class="required">*</span></label><input class="form-control" [(ngModel)]="clientForm()!.first_name"></div><div class="col-md-4"><label>Nom <span class="required">*</span></label><input class="form-control" [(ngModel)]="clientForm()!.last_name"></div><div class="col-md-4"><label>Téléphone <span class="required">*</span></label><div class="input-group"><input class="form-control" [(ngModel)]="clientForm()!.phone"><button class="btn btn-outline-secondary" type="button" (click)="findMatches()">Rechercher</button></div></div><div class="col-md-6"><label>E-mail <span class="text-muted">(facultatif)</span></label><input class="form-control" type="email" [(ngModel)]="clientForm()!.email"></div><div class="col-md-6"><label>Adresse / maison / quartier <span class="required">*</span></label><input class="form-control" [(ngModel)]="clientForm()!.address"></div><div class="col-md-6"><label>Résidence</label><input class="form-control" [(ngModel)]="clientForm()!.residence"></div><div class="col-md-6"><label>Numéro de pièce d’identité <span class="required">*</span></label><input class="form-control" [(ngModel)]="clientForm()!.id_document_number"></div><div class="col-md-6"><label>Permis de conduire <span class="required">*</span></label><input class="form-control" [(ngModel)]="clientForm()!.driving_license_number"></div><div class="col-md-6"><label>Expiration du permis <span class="required">*</span></label><input class="form-control" type="date" [(ngModel)]="clientForm()!.driving_license_expiry_date"></div><div class="col-md-6"><label>Contact d’urgence <span class="required">*</span></label><input class="form-control" [(ngModel)]="clientForm()!.emergency_contact_name"></div><div class="col-md-6"><label>Numéro du contact d’urgence <span class="required">*</span></label><input class="form-control" [(ngModel)]="clientForm()!.emergency_contact_phone"></div></div>
  @if(matches().length){<div class="alert alert-light border mt-3"><strong>Client(s) correspondant(s)</strong><p class="small mb-2">Sélectionnez un client existant pour éviter un doublon.</p>@for(client of matches();track client.id){<button class="btn btn-sm btn-outline-primary me-2 mb-1" (click)="useClient(client)">{{client.first_name}} {{client.last_name}} — {{client.phone}}</button>}</div>}
  <div class="row g-3 mt-1"><div class="col-md-4"><div class="document-upload"><label class="form-label">Pièce d’identité</label><input class="form-control" type="file" accept="image/png,image/jpeg,image/webp,application/pdf" (change)="chooseFile('identity_document',$event)">@if(fileName('identity_document')){<small>{{fileName('identity_document')}}</small>}</div></div><div class="col-md-4"><div class="document-upload"><label class="form-label">Permis de conduire</label><input class="form-control" type="file" accept="image/png,image/jpeg,image/webp,application/pdf" (change)="chooseFile('driving_license',$event)">@if(fileName('driving_license')){<small>{{fileName('driving_license')}}</small>}</div></div><div class="col-md-4"><div class="document-upload"><label class="form-label">Autre pièce</label><input class="form-control" type="file" accept="image/png,image/jpeg,image/webp,application/pdf" (change)="chooseFile('document',$event)">@if(fileName('document')){<small>{{fileName('document')}}</small>}</div></div></div>
  <button class="btn btn-primary mt-4" (click)="next()">Suivant</button>}
  @if(step()===2){<div class="row g-3"><div class="col-md-6"><label>Véhicule disponible <span class="required">*</span></label><select class="form-select" [(ngModel)]="rentalForm()!.vehicle_id" (change)="priceFromVehicle()"><option value="">Sélectionner un véhicule</option>@for(vehicle of vehicles();track vehicle.id){<option [value]="vehicle.id">{{vehicle.registration_number}} — {{vehicle.make}} {{vehicle.model}}</option>}</select></div><div class="col-md-3"><label>Départ <span class="required">*</span></label><input class="form-control" type="datetime-local" [(ngModel)]="rentalForm()!.departure_date" (change)="duration()"></div><div class="col-md-3"><label>Retour <span class="required">*</span></label><input class="form-control" type="datetime-local" [(ngModel)]="rentalForm()!.return_date" (change)="duration()"></div><div class="col-md-3"><label>Durée</label><input class="form-control" [value]="durationLabel()" readonly></div><div class="col-md-3"><label>Prix total <span class="required">*</span></label><input class="form-control" min="0" type="number" [(ngModel)]="rentalForm()!.rental_price"></div><div class="col-md-3"><label>Montant de la caution</label><input class="form-control" min="0" type="number" placeholder="0" [(ngModel)]="rentalForm()!.deposit_amount"></div><div class="col-md-3"><label>Statut</label><input class="form-control" value="En attente" readonly></div><div class="col-md-6"><label>Lieu de départ <span class="required">*</span></label><input class="form-control" [(ngModel)]="rentalForm()!.departure_location"></div><div class="col-md-6"><label>Lieu de retour <span class="required">*</span></label><input class="form-control" [(ngModel)]="rentalForm()!.return_location"></div><div class="col-md-6"><label>Zone de conduite</label><input class="form-control" [(ngModel)]="rentalForm()!.driving_zone"></div><div class="col-md-6"><label>Paiement reçu <span class="required">*</span></label><select class="form-select" [(ngModel)]="rentalForm()!.payment_received"><option [ngValue]="null">Choisir Oui ou Non</option><option [ngValue]="true">Oui, paiement reçu</option><option [ngValue]="false">Non, pas encore reçu</option></select><small class="text-muted">Ce choix est obligatoire et correspond à un encaissement physique.</small></div></div><button class="btn btn-outline-secondary mt-4 me-2" (click)="step.set(1)">Précédent</button><button class="btn btn-success mt-4" [disabled]="saving()" (click)="saveWizard()">{{saving()?'Enregistrement…':editingId()?'Enregistrer les modifications':'Créer la location'}}</button>}</div></section>}
  @if(selected()){<section class="card form-card mt-4"><div class="card-body"><div class="d-flex justify-content-between gap-3"><div><h2 class="h4">Fiche location</h2><p class="mb-0">{{selected().clients?.first_name}} {{selected().clients?.last_name}} — {{selected().vehicles?.registration_number}}</p></div><div class="d-flex gap-2 align-items-start"><span class="badge text-bg-{{statusTone(selected().status)}}">{{statusLabel(selected().status)}}</span><button class="btn btn-sm btn-outline-secondary" (click)="closeDetail()">Fermer</button></div></div><div class="row g-3 mt-2"><div class="col-md-4"><div class="border rounded p-3 h-100"><small class="text-muted d-block">Prix total</small><strong>{{money(selected().rental_price)}}</strong></div></div><div class="col-md-4"><div class="border rounded p-3 h-100"><small class="text-muted d-block">Paiement</small><strong [class.text-success]="paymentReceived()" [class.text-warning]="!paymentReceived()">{{paymentReceived()?'Reçu':'Non reçu'}}</strong><small class="d-block text-muted">Reçu : {{money(receivedAmount())}}</small></div></div><div class="col-md-4"><div class="border rounded p-3 h-100"><small class="text-muted d-block">Caution</small><strong>{{money(selected().deposit_amount)}}</strong></div></div></div>
  <hr><div class="row g-3"><div class="col-md-6"><h3 class="h6">Client</h3><p class="mb-1"><strong>{{selected().clients?.first_name}} {{selected().clients?.last_name}}</strong><br>{{selected().clients?.phone}}<br>{{selected().clients?.email||'E-mail non renseigné'}}<br>{{selected().clients?.address}} {{selected().clients?.residence||''}}</p><p class="small mb-0">Pièce : {{selected().clients?.id_document_number}}<br>Permis : {{selected().clients?.driving_license_number}} — expire le {{selected().clients?.driving_license_expiry_date|date:'mediumDate'}}<br>Urgence : {{selected().clients?.emergency_contact_name}} {{selected().clients?.emergency_contact_phone}}</p></div><div class="col-md-6"><h3 class="h6">Location</h3><p class="mb-1">Départ : {{selected().departure_date|date:'medium'}}<br>Retour : {{selected().return_date|date:'medium'}}<br>Durée : {{selected().duration_days}} jour(s)<br>Lieux : {{selected().departure_location||'—'}} → {{selected().return_location||'—'}}<br>Zone : {{selected().driving_zone||'—'}}</p></div></div>
  <div class="border rounded p-3 mt-3"><div class="d-flex flex-wrap justify-content-between gap-3 align-items-center"><div><h3 class="h6 mb-1">Paiement reçu</h3><p class="small text-muted mb-0">Le paiement est un encaissement physique enregistré avec la date et le responsable connecté.</p></div><div class="form-check form-switch fs-5"><input class="form-check-input" type="checkbox" role="switch" id="payment-received" [checked]="paymentReceived()" [disabled]="paymentSaving()||paymentReceived()||!auth.can('payments','create')" (change)="togglePayment($event)"><label class="form-check-label" for="payment-received">{{paymentReceived()?'Oui':'Non'}}</label></div></div>@if(paymentReceived()){<small class="d-block text-success mt-2">Paiement confirmé. Les informations de location sont verrouillées.</small>}@else{<small class="d-block text-muted mt-2">Le paiement peut être confirmé ici plus tard.</small>}</div>
  <div class="mt-3"><h3 class="h6">Pièces du client</h3><div class="detail-docs">@for(document of documents();track document.id){<button class="btn btn-sm btn-outline-primary" (click)="openDocument(document)">Voir {{document.document_name}}</button>}@empty{<small class="text-muted">Aucune pièce envoyée.</small>}</div></div><h3 class="h6 mt-4">Historique des statuts</h3>@for(item of history();track item.id){<p class="small mb-1">{{item.created_at|date:'short'}} — {{statusLabel(item.old_status)||'—'}} → {{statusLabel(item.new_status)}} — par <strong>{{actorName(item.changed_by)}}</strong></p>}@empty{<p class="small text-muted">Aucun changement de statut.</p>}<div class="d-flex flex-wrap gap-2 mt-3">@if(canEdit()){<button class="btn btn-primary btn-sm" (click)="openEdit(selected())">Modifier</button>}@if(auth.can('payments','view')){<a class="btn btn-outline-success btn-sm" routerLink="/payments">Historique financier</a>}@if(auth.can('inspections','view')){<a class="btn btn-outline-primary btn-sm" routerLink="/inspections" [queryParams]="{rental:selected().id}">Inspections</a>}</div></div></section>}
  `
})
export class RentalsComponent implements OnInit {
  rows=signal<any[]>([]); vehicles=signal<any[]>([]); matches=signal<any[]>([]); documents=signal<any[]>([]); history=signal<any[]>([]); selectedPayments=signal<any[]>([]);
  wizard=signal(false); step=signal(1); editingId=signal<string|null>(null); selected=signal<any>(null); clientForm=signal<any>(null); rentalForm=signal<any>(null);
  loading=signal(false); saving=signal(false); paymentSaving=signal(false); error=signal(''); message=signal(''); search=''; filter=''; private files=new Map<string,File>();
  readonly statuses=['pending','active','overdue','completed'];
  constructor(public auth:AuthService,private actors:ActorNamesService){}
  ngOnInit(){void this.load()}
  clearFeedback(){this.error.set('');this.message.set('')}
  async refreshStatuses(){const result=await this.auth.supabase().rpc('refresh_overdue_rentals');if(result.error)this.error.set(this.auth.errorMessage(result.error))}
  async load(){this.loading.set(true);this.clearFeedback();await this.refreshStatuses();let query=this.auth.supabase().from('rentals').select('*,clients(first_name,last_name,phone),vehicles(registration_number,make,model),payments(amount)').order('departure_date',{ascending:false});if(this.filter)query=query.eq('status',this.filter);const result=await query;let data=result.data??[];if(this.search){const term=this.search.toLowerCase();data=data.filter(item=>((item.clients?.first_name??'')+' '+(item.clients?.last_name??'')+' '+(item.vehicles?.registration_number??'')).toLowerCase().includes(term))}this.rows.set(data.map(item=>({...item,payment_received:(item.payments??[]).reduce((sum:any,payment:any)=>sum+Number(payment.amount??0),0)>=Number(item.rental_price??0)})));if(result.error)this.error.set(this.auth.errorMessage(result.error));this.loading.set(false)}
  async loadVehicles(){const result=await this.auth.supabase().from('vehicles').select('id,registration_number,make,model,rental_price,deposit_amount').eq('status','available').order('registration_number');this.vehicles.set(result.data??[]);if(result.error)this.error.set(this.auth.errorMessage(result.error))}
  openNew(){this.clearFeedback();this.selected.set(null);this.documents.set([]);this.history.set([]);this.selectedPayments.set([]);this.files.clear();this.matches.set([]);this.editingId.set(null);this.clientForm.set({first_name:'',last_name:'',phone:'',email:'',id_document_number:'',driving_license_number:'',driving_license_expiry_date:'',emergency_contact_name:'',emergency_contact_phone:'',address:'',residence:'',id:null});this.rentalForm.set({vehicle_id:'',departure_date:'',return_date:'',duration_days:0,departure_location:'',return_location:'',rental_price:0,deposit_amount:0,driving_zone:'',payment_received:null});this.step.set(1);this.wizard.set(true);void this.loadVehicles()}
  closeWizard(){this.wizard.set(false);this.files.clear();this.matches.set([]);this.editingId.set(null)}
  async findMatches(){const phone=this.clientForm()?.phone?.trim();if(!phone){this.error.set('Saisissez le téléphone avant de rechercher un client.');return}const result=await this.auth.supabase().from('clients').select('*').eq('phone',phone).order('last_name');this.matches.set(result.data??[]);if(result.error)this.error.set(this.auth.errorMessage(result.error))}
  useClient(client:any){this.clientForm.set({...client});this.matches.set([]);this.message.set('Client existant sélectionné. Ses données restent modifiables tant que la location est en attente.')}
  chooseFile(type:string,event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(file)this.files.set(type,file)}
  fileName(type:string){return this.files.get(type)?.name??''}
  validClient(){const c=this.clientForm();return !!(c?.first_name?.trim()&&c?.last_name?.trim()&&c?.phone?.trim()&&c?.id_document_number?.trim()&&c?.driving_license_number?.trim()&&c?.driving_license_expiry_date&&c?.emergency_contact_name?.trim()&&c?.emergency_contact_phone?.trim()&&c?.address?.trim())}
  next(){this.clearFeedback();if(!this.validClient()){this.error.set('Veuillez renseigner toutes les informations client obligatoires.');return}this.step.set(2)}
  priceFromVehicle(){const vehicle=this.vehicles().find(item=>item.id===this.rentalForm()?.vehicle_id);if(vehicle)this.rentalForm.set({...this.rentalForm(),rental_price:vehicle.rental_price??0,deposit_amount:vehicle.deposit_amount??0})}
  duration(){const form=this.rentalForm();if(form?.departure_date&&form.return_date){const days=(new Date(form.return_date).getTime()-new Date(form.departure_date).getTime())/86400000;this.rentalForm.set({...form,duration_days:days>0?days:0})}}
  durationLabel(){const value=Number(this.rentalForm()?.duration_days??0);if(!value)return '—';return value===1?'1 jour':value.toLocaleString('fr-FR',{maximumFractionDigits:2})+' jours'}
  validRental(){const r=this.rentalForm();return !!(r?.vehicle_id&&r?.departure_date&&r?.return_date&&r?.departure_location?.trim()&&r?.return_location?.trim()&&r.payment_received!==null&&r.payment_received!==undefined&&Number(r.rental_price)>=0&&Number(r.deposit_amount??0)>=0&&new Date(r.return_date)>new Date(r.departure_date))}
  async saveWizard(){this.clearFeedback();if(!this.validRental()){this.error.set('Veuillez renseigner les informations location obligatoires, choisir le paiement reçu et vérifier les dates.');return}this.saving.set(true);const client=this.clientForm(),rental=this.rentalForm();if(this.editingId()){const clientUpdate=await this.auth.supabase().from('clients').update(this.clientPayload(client)).eq('id',client.id);const rentalUpdate=clientUpdate.error?null:await this.auth.supabase().from('rentals').update(this.rentalPayload(rental)).eq('id',this.editingId()!);this.saving.set(false);if(clientUpdate.error||rentalUpdate?.error){this.error.set(this.auth.errorMessage(clientUpdate.error??rentalUpdate?.error));return}await this.uploadDocuments(client.id);this.message.set('Location et informations client mises à jour.');this.closeWizard();await this.load();return}const result=await this.auth.supabase().rpc('create_rental_from_wizard',{target_existing_client_id:client.id||null,target_first_name:client.first_name,target_last_name:client.last_name,target_phone:client.phone,target_email:client.email||null,target_id_document_number:client.id_document_number,target_driving_license_number:client.driving_license_number,target_driving_license_expiry_date:client.driving_license_expiry_date,target_emergency_contact_name:client.emergency_contact_name,target_emergency_contact_phone:client.emergency_contact_phone,target_address:client.address,target_residence:client.residence||null,target_vehicle_id:rental.vehicle_id,target_departure_date:new Date(rental.departure_date).toISOString(),target_return_date:new Date(rental.return_date).toISOString(),target_departure_location:rental.departure_location,target_return_location:rental.return_location,target_rental_price:Number(rental.rental_price),target_deposit_amount:Number(rental.deposit_amount||0),target_driving_zone:rental.driving_zone||null,target_payment_received:rental.payment_received});this.saving.set(false);if(result.error){this.error.set(this.auth.errorMessage(result.error));return}const data=result.data as any;const documentsOk=await this.uploadDocuments(data.client_id);this.message.set(documentsOk?'Location créée avec succès.':'Location créée, mais une ou plusieurs pièces n’ont pas pu être envoyées.');this.closeWizard();await this.load()}
  clientPayload(c:any){return{first_name:c.first_name.trim(),last_name:c.last_name.trim(),phone:c.phone.trim(),email:c.email||null,id_document_number:c.id_document_number.trim(),driving_license_number:c.driving_license_number.trim(),driving_license_expiry_date:c.driving_license_expiry_date,emergency_contact_name:c.emergency_contact_name.trim(),emergency_contact_phone:c.emergency_contact_phone.trim(),address:c.address.trim(),residence:c.residence||null}}
  rentalPayload(r:any){return{vehicle_id:r.vehicle_id,departure_date:new Date(r.departure_date).toISOString(),return_date:new Date(r.return_date).toISOString(),duration_days:Number(r.duration_days),departure_location:r.departure_location.trim(),return_location:r.return_location.trim(),rental_price:Number(r.rental_price),deposit_amount:Number(r.deposit_amount||0),driving_zone:r.driving_zone||null}}
  async uploadDocuments(clientId:string){let success=true;for(const[type,file]of this.files){const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const path='clients/'+clientId+'/'+crypto.randomUUID()+'-'+safe;const upload=await this.auth.supabase().storage.from('rental-documents').upload(path,file,{contentType:file.type,upsert:false});if(upload.error){success=false;continue}const saved=await this.auth.supabase().from('client_documents').insert({client_id:clientId,document_type:type,document_name:file.name,storage_path:path,mime_type:file.type,file_size:file.size});if(saved.error)success=false}return success}
  async detail(rental:any){this.clearFeedback();await this.refreshStatuses();const[latest,history,payments]=await Promise.all([this.auth.supabase().from('rentals').select('*,clients(*),vehicles(registration_number,make,model)').eq('id',rental.id).single(),this.auth.supabase().from('rental_status_history').select('*').eq('rental_id',rental.id).order('created_at'),this.auth.supabase().from('payments').select('id,amount,payment_date,recorded_by,reference').eq('rental_id',rental.id).order('payment_date',{ascending:false})]);this.selected.set(latest.data??rental);this.history.set(history.data??[]);this.selectedPayments.set(payments.data??[]);await this.actors.load([...(history.data??[]).map(item=>item.changed_by),...(payments.data??[]).map(item=>item.recorded_by)]);if(latest.data?.client_id){const docs=await this.auth.supabase().from('client_documents').select('*').eq('client_id',latest.data.client_id).order('created_at',{ascending:false});this.documents.set(docs.data??[]);if(docs.error)this.error.set(this.auth.errorMessage(docs.error))}if(latest.error||history.error||payments.error)this.error.set(this.auth.errorMessage(latest.error??history.error??payments.error))}
  closeDetail(){this.selected.set(null);this.documents.set([]);this.history.set([]);this.selectedPayments.set([])}
  receivedAmount(){return this.selectedPayments().reduce((sum,payment)=>sum+Number(payment.amount??0),0)} paymentReceived(){return!!this.selected()&&this.receivedAmount()>=Number(this.selected().rental_price??0)&&Number(this.selected().rental_price??0)>=0} canEdit(){return this.auth.can('rentals','update')&&this.selected()?.status==='pending'&&!this.paymentReceived()}
  async openEdit(rental:any){this.clearFeedback();this.selected.set(null);this.documents.set([]);this.history.set([]);this.selectedPayments.set([]);await this.loadVehicles();const client=rental.clients??{};this.clientForm.set({...client});this.rentalForm.set({...rental,departure_date:this.localDate(rental.departure_date),return_date:this.localDate(rental.return_date),payment_received:false});this.editingId.set(rental.id);this.files.clear();this.step.set(1);this.wizard.set(true)}
  localDate(value:string){return value?new Date(value).toISOString().slice(0,16):''}
  async togglePayment(event:Event){const checked=(event.target as HTMLInputElement).checked;const rental=this.selected();if(!rental)return;this.clearFeedback();if(!checked){this.error.set('Un paiement déjà enregistré ne peut pas être remis à Non reçu depuis cette fiche.');return}if(this.paymentReceived()){this.message.set('Le paiement total est déjà confirmé.');return}this.paymentSaving.set(true);const result=await this.auth.supabase().rpc('confirm_rental_payment',{target_rental_id:rental.id});this.paymentSaving.set(false);if(result.error){this.error.set(this.auth.errorMessage(result.error));return}this.message.set('Paiement total reçu et enregistré. Les informations sont maintenant verrouillées.');await this.detail(rental);await this.load()}
  async openDocument(document:any){const result=await this.auth.supabase().storage.from('rental-documents').createSignedUrl(document.storage_path,60);if(result.error)this.error.set(this.auth.errorMessage(result.error));else window.open(result.data.signedUrl,'_blank','noopener')}
  actorName(id:string|null|undefined){return this.actors.label(id)}
  money(value:unknown){return Number(value??0).toLocaleString('fr-FR')+' FCFA'} statusLabel(status:string|undefined){return({pending:'En attente',active:'En cours',overdue:'En retard',completed:'Terminée'}as Record<string,string>)[status??'']??status??''} statusTone(status:string){return({pending:'warning',active:'primary',overdue:'danger',completed:'success'}as Record<string,string>)[status]??'secondary'}
}




