import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { AuthService } from '../core/auth.service';
@Component({standalone:true,imports:[FormsModule],template:`
<div class="page-heading"><div><p class="eyebrow">PILOTAGE</p><h1>Rapports</h1><p>Une synthèse fondée sur les encaissements réellement enregistrés.</p></div><button class="btn btn-outline-primary" (click)="csv()">Exporter CSV</button></div>
<div class="toolbar row g-2"><div class="col-sm-4"><input class="form-control" type="date" [(ngModel)]="from"></div><div class="col-sm-4"><input class="form-control" type="date" [(ngModel)]="to"></div><div class="col-sm-4"><button class="btn btn-primary w-100" (click)="load()">Appliquer la période</button></div></div>
@if(error()){<div class="alert alert-danger">{{error()}}</div>}@if(loading()){<div class="empty-state">Calcul des indicateurs…</div>}@else{<div class="row g-3">@for(x of stats();track x.label){<div class="col-sm-6 col-xl-3"><div class="metric-card"><small>{{x.label}}</small><strong>{{x.value}}</strong></div></div>}</div><div class="row g-3 mt-1"><div class="col-lg-6"><section class="card h-100"><div class="card-body"><h2 class="h5">CA par véhicule</h2>@for(x of revenueByVehicle();track x.name){<div class="d-flex justify-content-between border-bottom py-2"><span>{{x.name}}</span><strong>{{x.amount}}</strong></div>}@empty{<p class="text-muted mb-0">Aucun encaissement sur cette période.</p>}</div></section></div><div class="col-lg-6"><section class="card h-100"><div class="card-body"><h2 class="h5">Véhicules les plus loués</h2>@for(x of topVehicles();track x.name){<div class="d-flex justify-content-between border-bottom py-2"><span>{{x.name}}</span><strong>{{x.count}} location(s)</strong></div>}@empty{<p class="text-muted mb-0">Aucune location sur cette période.</p>}</div></section></div></div>}`})
export class ReportsComponent implements OnInit{from='';to='';error=signal('');loading=signal(false);stats=signal<any[]>([]);revenueByVehicle=signal<any[]>([]);topVehicles=signal<any[]>([]);constructor(private auth:AuthService){}ngOnInit(){const now=new Date();this.from=`${now.getFullYear()}-01-01`;this.to=now.toISOString().slice(0,10);this.load()}private between(date:string|undefined){return !!date&&(!this.from||date>=this.from)&&(!this.to||date<=this.to)}async load(){this.loading.set(true);this.error.set('');const[p,r,i,m]=await Promise.all([this.auth.supabase().from('payments').select('amount,payment_date,rental_id,rentals(vehicles(make,model,registration_number))'),this.auth.supabase().from('rentals').select('id,departure_date,client_id,vehicles(make,model,registration_number)'),this.auth.supabase().from('incidents').select('cost,incident_date'),this.auth.supabase().from('vehicle_maintenance').select('cost,maintenance_date')]);this.loading.set(false);const e=p.error??r.error??i.error??m.error;if(e){this.error.set(this.auth.errorMessage(e));return}const payments=(p.data??[]).filter((x:any)=>this.between(x.payment_date)),rentals=(r.data??[]).filter((x:any)=>this.between(x.departure_date)),incidents=(i.data??[]).filter((x:any)=>this.between(x.incident_date)),maintenance=(m.data??[]).filter((x:any)=>this.between(x.maintenance_date));const revenue=payments.reduce((s:number,x:any)=>s+Number(x.amount||0),0),costs=maintenance.reduce((s:number,x:any)=>s+Number(x.cost||0),0);this.stats.set([{label:'Revenus encaissés',value:revenue.toLocaleString('fr-FR')+' FCFA'},{label:'Locations',value:rentals.length},{label:'Clients actifs',value:new Set(rentals.map((x:any)=>x.client_id)).size},{label:'Incidents',value:incidents.length},{label:'Coûts maintenance',value:costs.toLocaleString('fr-FR')+' FCFA'}]);const rev=new Map<string,number>();for(const x of payments){const rental:any=Array.isArray(x.rentals)?x.rentals[0]:x.rentals,car=rental?.vehicles;const name=car?`${car.make||''} ${car.model||''} · ${car.registration_number||''}`.trim():'Location non liée';rev.set(name,(rev.get(name)||0)+Number(x.amount||0))}this.revenueByVehicle.set([...rev].sort((a,b)=>b[1]-a[1]).map(([name,amount])=>({name,amount:amount.toLocaleString('fr-FR')+' FCFA'})));const top=new Map<string,number>();for(const x of rentals){const car:any=Array.isArray(x.vehicles)?x.vehicles[0]:x.vehicles,name=car?`${car.make||''} ${car.model||''} · ${car.registration_number||''}`.trim():'Véhicule';top.set(name,(top.get(name)||0)+1)}this.topVehicles.set([...top].sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name,count})))}csv(){const text=['Indicateur;Valeur',...this.stats().map(x=>`${x.label};${x.value}`)].join('\n'),link=document.createElement('a');link.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));link.download='rapport-location.csv';link.click();URL.revokeObjectURL(link.href)}}


