import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from '../core/auth.service';

@Component({standalone:true,imports:[FormsModule],template:`
<div class="page-heading"><div><p class="eyebrow">FINALISATION</p><h1>Client de la réservation</h1><p>Complétez ou sélectionnez le client avant de créer la location.</p></div></div>
@if(error()){<div class="alert alert-danger">{{error()}}</div>}@if(message()){<div class="alert alert-info">{{message()}}</div>}@if(loading()){<div class="empty-state">Chargement…</div>}@else if(!reservation()){<div class="alert alert-warning">Cette réservation est introuvable ou n’est plus active.</div>}@else{<section class="card form-card"><div class="card-body"><p><strong>Réservation :</strong> {{reservation().first_name}} {{reservation().last_name}} — {{reservation().phone}}</p>@if(matches().length){<div class="alert alert-light border"><strong>Client existant trouvé</strong><div class="mt-2 d-flex flex-wrap gap-2">@for(client of matches();track client.id){<button class="btn btn-sm btn-outline-primary" (click)="use(client)">{{client.first_name}} {{client.last_name}} — {{client.phone}}</button>}</div></div>}<div class="row g-3"><div class="col-md-4"><label>Prénom <span class="required">*</span></label><input class="form-control" [(ngModel)]="form()!.first_name"></div><div class="col-md-4"><label>Nom <span class="required">*</span></label><input class="form-control" [(ngModel)]="form()!.last_name"></div><div class="col-md-4"><label>Téléphone <span class="required">*</span></label><input class="form-control" [(ngModel)]="form()!.phone"></div><div class="col-md-6"><label>Adresse / résidence</label><input class="form-control" [(ngModel)]="form()!.address"></div><div class="col-md-6"><label>E-mail</label><input class="form-control" [(ngModel)]="form()!.email"></div><div class="col-md-4"><label>Pièce d’identité</label><input class="form-control" [(ngModel)]="form()!.id_document_number"></div><div class="col-md-4"><label>Permis</label><input class="form-control" [(ngModel)]="form()!.driving_license_number"></div><div class="col-md-4"><label>Expiration permis</label><input class="form-control" type="date" [(ngModel)]="form()!.driving_license_expiry_date"></div><div class="col-md-6"><label>Contact d’urgence</label><input class="form-control" [(ngModel)]="form()!.emergency_contact_name"></div><div class="col-md-6"><label>Téléphone urgence</label><input class="form-control" [(ngModel)]="form()!.emergency_contact_phone"></div></div><button class="btn btn-primary mt-4" [disabled]="saving()" (click)="save()">{{saving()?'Enregistrement…':'Continuer vers la location'}}</button><button class="btn btn-link mt-4" (click)="back()">Retour</button></div></section>}
`})
export class ReservationClientComponent implements OnInit {
  reservation=signal<any>(null); matches=signal<any[]>([]); form=signal<any>({}); loading=signal(true); saving=signal(false); error=signal(''); message=signal(''); private id='';
  constructor(private route:ActivatedRoute,private router:Router,private auth:AuthService){}
  async ngOnInit(){this.id=this.route.snapshot.queryParamMap.get('reservation')??'';if(!this.id){this.loading.set(false);return}const result=await this.auth.supabase().from('reservations').select('*').eq('id',this.id).eq('status','pending').maybeSingle();if(result.error){this.error.set(this.auth.errorMessage(result.error));this.loading.set(false);return}this.reservation.set(result.data);if(result.data){this.form.set({first_name:result.data.first_name,last_name:result.data.last_name,phone:result.data.phone,address:'',email:'',id_document_number:'',driving_license_number:'',driving_license_expiry_date:'',emergency_contact_name:'',emergency_contact_phone:''});const matches=await this.auth.supabase().from('clients').select('*').eq('phone',result.data.phone).order('last_name');this.matches.set(matches.data??[])}this.loading.set(false)}
  use(client:any){this.form.set({...client});this.message.set('Client existant sélectionné. Vérifiez ses informations avant de continuer.')}
  async save(){const value=this.form();if(!value.first_name?.trim()||!value.last_name?.trim()||!value.phone?.trim()){this.error.set('Prénom, nom et téléphone sont obligatoires.');return}this.saving.set(true);const result=value.id?await this.auth.supabase().from('clients').update(value).eq('id',value.id).select().single():await this.auth.supabase().from('clients').insert(value).select().single();this.saving.set(false);if(result.error){this.error.set(this.auth.errorMessage(result.error));return}await this.router.navigate(['/reservation-rental'],{queryParams:{reservation:this.id,client:result.data.id}})}
  back(){void this.router.navigate(['/reservations'])}
}
