import { AfterViewInit, Component, ElementRef, OnDestroy, OnInit, ViewChild, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Calendar } from '@fullcalendar/core';
import frLocale from '@fullcalendar/core/locales/fr';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import interactionPlugin from '@fullcalendar/interaction';
import { AuthService } from '../core/auth.service';

@Component({
  standalone: true,
  imports: [FormsModule, DatePipe],
  styles: ['.reservation-calendar{min-height:650px}.reservation-calendar .fc-event{white-space:normal;cursor:pointer}@media(max-width:760px){.reservation-calendar{min-height:520px;font-size:.78rem}.reservation-calendar .fc-toolbar{flex-wrap:wrap;gap:.5rem}.reservation-calendar .fc-toolbar-title{font-size:1.05rem}}'],
  template: `
    <div class="page-heading"><div><p class="eyebrow">PLANIFICATION</p><h1>Réservations</h1><p>Les réservations en attente bloquent le véhicule jusqu’à leur finalisation ou annulation.</p></div>@if(auth.can('reservations','create')){<button class="btn btn-primary" (click)="openNew()">+ Nouvelle réservation</button>}</div>
    <div class="toolbar row g-2"><div class="col-md-5"><input class="form-control" [(ngModel)]="query" (input)="refresh()" placeholder="Nom, téléphone ou véhicule"></div><div class="col-md-4"><select class="form-select" [(ngModel)]="vehicleFilter" (change)="refresh()"><option value="">Tous les véhicules</option>@for(vehicle of vehicles();track vehicle.id){<option [value]="vehicle.id">{{vehicle.registration_number}} — {{vehicle.make}} {{vehicle.model}}</option>}</select></div><div class="col-md-3"><select class="form-select" [(ngModel)]="statusFilter" (change)="refresh()"><option value="pending">Actives : en attente</option><option value="finalized">Finalisées</option><option value="cancelled">Annulées</option><option value="">Tous les statuts</option></select></div></div>
    @if(error()){<div class="alert alert-danger">{{error()}}</div>}@if(message()){<div class="alert alert-success">{{message()}}</div>}@if(loading()){<div class="empty-state">Chargement des réservations…</div>}@else{<div class="card mb-4"><div class="card-body"><div #calendarHost class="reservation-calendar"></div></div></div>@if(!visible().length){<div class="empty-state">Aucune réservation avec ces filtres.</div>}@else{<div class="table-responsive app-table"><table class="table align-middle mb-0"><thead><tr><th>Client</th><th>Véhicule</th><th>Période</th><th>Statut</th><th class="text-end">Actions</th></tr></thead><tbody>@for(item of visible();track item.id){<tr><td><strong>{{item.first_name}} {{item.last_name}}</strong><small class="d-block text-muted">{{item.phone}}</small></td><td>{{item.vehicles?.registration_number}}</td><td>{{item.planned_departure_date|date:'short'}}<small class="d-block text-muted">au {{item.planned_return_date|date:'short'}}</small></td><td><span class="badge text-bg-{{tone(item.status)}}">{{label(item.status)}}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary me-1" (click)="show(item)">Voir</button>@if(item.status==='pending'&&auth.can('reservations','update')){<button class="btn btn-sm btn-outline-secondary me-1" (click)="openEdit(item)">Modifier</button><button class="btn btn-sm btn-success me-1" (click)="finalize(item)">Finaliser</button><button class="btn btn-sm btn-outline-danger" (click)="cancel(item)">Annuler</button>}</td></tr>}</tbody></table></div>}}
    @if(form()){<section class="card form-card mt-4"><div class="card-body"><h2 class="h4">{{form()!.id?'Modifier':'Nouvelle'}} réservation</h2><p class="text-muted">Le statut est créé automatiquement à « En attente ».</p><div class="row g-3"><div class="col-md-4"><label>Prénom <span class="required">*</span></label><input class="form-control" [(ngModel)]="form()!.first_name"></div><div class="col-md-4"><label>Nom <span class="required">*</span></label><input class="form-control" [(ngModel)]="form()!.last_name"></div><div class="col-md-4"><label>Téléphone <span class="required">*</span></label><input class="form-control" [(ngModel)]="form()!.phone"></div><div class="col-md-6"><label>Véhicule <span class="required">*</span></label><select class="form-select" [(ngModel)]="form()!.vehicle_id"><option value="">Sélectionner un véhicule</option>@for(vehicle of vehicles();track vehicle.id){<option [value]="vehicle.id">{{vehicle.registration_number}} — {{vehicle.make}} {{vehicle.model}}</option>}</select></div><div class="col-md-3"><label>Départ prévu <span class="required">*</span></label><input class="form-control" type="datetime-local" [(ngModel)]="form()!.planned_departure_date"></div><div class="col-md-3"><label>Retour prévu <span class="required">*</span></label><input class="form-control" type="datetime-local" [(ngModel)]="form()!.planned_return_date"></div><div class="col-12"><label>Observation</label><textarea class="form-control" rows="3" [(ngModel)]="form()!.observation"></textarea></div></div><button class="btn btn-primary mt-3" [disabled]="saving()" (click)="save()">{{saving()?'Enregistrement…':'Enregistrer'}}</button><button class="btn btn-link mt-3" (click)="form.set(null)">Annuler</button></div></section>}
    @if(selected()){<section class="card form-card mt-4"><div class="card-body"><div class="d-flex justify-content-between"><div><h2 class="h4">Réservation {{label(selected().status).toLowerCase()}}</h2><p class="mb-0">{{selected().first_name}} {{selected().last_name}} — {{selected().phone}}</p></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-secondary" (click)="selected.set(null)">Fermer</button><button class="btn-close" (click)="selected.set(null)"></button></div></div><dl class="row mt-3 mb-0"><dt class="col-sm-3">Véhicule</dt><dd class="col-sm-9">{{selected().vehicles?.registration_number}}</dd><dt class="col-sm-3">Période</dt><dd class="col-sm-9">{{selected().planned_departure_date|date:'medium'}} → {{selected().planned_return_date|date:'medium'}}</dd><dt class="col-sm-3">Observation</dt><dd class="col-sm-9">{{selected().observation||'—'}}</dd>@if(selected().status==='cancelled'){<dt class="col-sm-3">Annulation</dt><dd class="col-sm-9">{{selected().cancelled_at|date:'short'}} — {{selected().cancellation_reason||'Sans motif'}}</dd>}@if(selected().status==='finalized'){<dt class="col-sm-3">Location créée</dt><dd class="col-sm-9">{{selected().rental_id||'—'}}</dd>}</dl></div></section>}
  `
})
export class ReservationsComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('calendarHost') calendarHost?: ElementRef<HTMLElement>;
  calendar?: Calendar; rows = signal<any[]>([]); vehicles = signal<any[]>([]); form = signal<any>(null); selected = signal<any>(null);
  loading = signal(false); saving = signal(false); error = signal(''); message = signal(''); query = ''; vehicleFilter = ''; statusFilter = 'pending';
  constructor(public auth: AuthService, private router: Router) {}
  ngOnInit() { void this.load(); } ngAfterViewInit() { this.createCalendar(); } ngOnDestroy() { this.calendar?.destroy(); }
  async load() { this.loading.set(true); const [vehicles, reservations] = await Promise.all([this.auth.supabase().from('vehicles').select('id,registration_number,make,model').order('registration_number'), this.auth.supabase().from('reservations').select('*,vehicles(registration_number,make,model)').order('planned_departure_date', { ascending: false })]); this.loading.set(false); this.vehicles.set(vehicles.data ?? []); this.rows.set(reservations.data ?? []); this.error.set(vehicles.error ? this.auth.errorMessage(vehicles.error) : reservations.error ? this.auth.errorMessage(reservations.error) : ''); this.refresh(); }
  visible() { return this.filtered(true); } calendarItems() { return this.filtered(false); }
  filtered(withStatus: boolean) { const term = this.query.trim().toLowerCase(); return this.rows().filter(item => (!withStatus || !this.statusFilter || item.status === this.statusFilter) && (!this.vehicleFilter || item.vehicle_id === this.vehicleFilter) && (!term || (item.first_name + ' ' + item.last_name + ' ' + item.phone + ' ' + (item.vehicles?.registration_number ?? '')).toLowerCase().includes(term))); }
  refresh() { if (!this.calendar) return; this.calendar.removeAllEvents(); this.calendar.addEventSource(this.calendarItems().map(item => ({ id: item.id, title: (item.vehicles?.registration_number ?? 'Véhicule') + ' · ' + item.first_name + ' ' + item.last_name + ' · ' + item.phone, start: item.planned_departure_date, end: item.planned_return_date, color: item.status === 'pending' ? '#0b9cac' : item.status === 'finalized' ? '#198754' : '#6c757d', extendedProps: { reservation: item } }))); }
  createCalendar() { if (!this.calendarHost) return; this.calendar = new Calendar(this.calendarHost.nativeElement, { plugins: [dayGridPlugin, timeGridPlugin, interactionPlugin], initialView: 'dayGridMonth', locales: [frLocale], locale: 'fr', firstDay: 1, headerToolbar: { left: 'prev,next today', center: 'title', right: 'dayGridMonth,timeGridWeek,timeGridDay' }, buttonText: { today: 'Aujourd’hui', month: 'Mois', week: 'Semaine', day: 'Jour' }, height: 'auto', eventClick: info => this.show(info.event.extendedProps['reservation']) }); this.calendar.render(); this.refresh(); }
  openNew() { this.error.set(''); this.message.set(''); this.selected.set(null); this.form.set({ first_name: '', last_name: '', phone: '', vehicle_id: '', planned_departure_date: '', planned_return_date: '', observation: '' }); }
  openEdit(item: any) { this.error.set(''); this.message.set(''); this.form.set({ ...item, planned_departure_date: this.local(item.planned_departure_date), planned_return_date: this.local(item.planned_return_date) }); }
  local(value: string) { return value ? new Date(value).toISOString().slice(0, 16) : ''; }
  async save() { const value = this.form(); if (!value?.first_name?.trim() || !value?.last_name?.trim() || !value?.phone?.trim() || !value?.vehicle_id || !value?.planned_departure_date || !value?.planned_return_date) { this.error.set('Prénom, nom, téléphone, véhicule et période sont obligatoires.'); return; } this.saving.set(true); const payload = { first_name: value.first_name.trim(), last_name: value.last_name.trim(), phone: value.phone.trim(), vehicle_id: value.vehicle_id, planned_departure_date: new Date(value.planned_departure_date).toISOString(), planned_return_date: new Date(value.planned_return_date).toISOString(), observation: value.observation || null }; const result = value.id ? await this.auth.supabase().from('reservations').update(payload).eq('id', value.id) : await this.auth.supabase().from('reservations').insert(payload); this.saving.set(false); if (result.error) { this.error.set(this.auth.errorMessage(result.error)); return; } this.form.set(null); this.message.set('Réservation enregistrée.'); await this.load(); }
  show(item: any) { this.selected.set(item); } finalize(item: any) { void this.router.navigate(['/reservation-client'], { queryParams: { reservation: item.id } }); }
  async cancel(item: any) { if (!confirm('Annuler la réservation de ' + item.first_name + ' ' + item.last_name + ' ?')) return; const reason = prompt('Motif d’annulation (facultatif)') ?? ''; const result = await this.auth.supabase().rpc('cancel_reservation', { target_reservation_id: item.id, reason }); if (result.error) { this.error.set(this.auth.errorMessage(result.error)); return; } this.message.set('Réservation annulée. Le véhicule est immédiatement libéré.'); this.selected.set(null); await this.load(); }
  label(status: string) { return ({ pending: 'En attente', finalized: 'Finalisée', cancelled: 'Annulée' } as Record<string, string>)[status] ?? status; } tone(status: string) { return ({ pending: 'warning', finalized: 'success', cancelled: 'secondary' } as Record<string, string>)[status] ?? 'secondary'; }
}


