import { Component, OnInit, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { AuthService } from '../core/auth.service';

@Component({standalone:true,imports:[FormsModule,DatePipe],template:`
<div class="page-heading"><div><p class="eyebrow">FINALISATION</p><h1>Créer la location</h1><p>Les informations prévues de la réservation sont conservées. Complétez les données propres à la location.</p></div></div>
@if(error()){<div class="alert alert-danger">{{error()}}</div>}@if(loading()){<div class="empty-state">Chargement de la réservation…</div>}@else if(!reservation()){<div class="alert alert-warning">Cette réservation est introuvable ou n’est plus active.</div>}@else{<section class="card form-card"><div class="card-body"><div class="alert alert-light border"><strong>{{reservation().first_name}} {{reservation().last_name}}</strong> — {{vehicle()?.registration_number}}<br><small>{{reservation().planned_departure_date|date:'short'}} au {{reservation().planned_return_date|date:'short'}}</small></div><div class="row g-3"><div class="col-md-6"><label>Lieu de départ</label><input class="form-control" [(ngModel)]="form()!.departure_location"></div><div class="col-md-6"><label>Lieu de retour</label><input class="form-control" [(ngModel)]="form()!.return_location"></div><div class="col-md-4"><label>Prix total <span class="required">*</span></label><input class="form-control" min="0" type="number" [(ngModel)]="form()!.rental_price"></div><div class="col-md-4"><label>Montant de la caution</label><input class="form-control" min="0" type="number" placeholder="0" [(ngModel)]="form()!.deposit_amount"></div><div class="col-md-4"><label>Zone de conduite</label><input class="form-control" [(ngModel)]="form()!.driving_zone"></div><div class="col-12"><label>Observation</label><textarea rows="3" class="form-control" [(ngModel)]="form()!.notes"></textarea></div></div><button class="btn btn-success mt-4" [disabled]="saving()" (click)="save()">{{saving()?'Création…':'Créer la location et finaliser la réservation'}}</button><button class="btn btn-link mt-4" (click)="back()">Retour</button></div></section>}
`})
export class ReservationRentalComponent implements OnInit {
  reservation=signal<any>(null); vehicle=signal<any>(null); form=signal<any>({}); loading=signal(true); saving=signal(false); error=signal(''); private reservationId=''; private clientId='';
  constructor(private route:ActivatedRoute,private router:Router,private auth:AuthService){}
  async ngOnInit(){this.reservationId=this.route.snapshot.queryParamMap.get('reservation')??'';this.clientId=this.route.snapshot.queryParamMap.get('client')??'';if(!this.reservationId||!this.clientId){this.loading.set(false);return}const reservation=await this.auth.supabase().from('reservations').select('*').eq('id',this.reservationId).eq('status','pending').maybeSingle();if(reservation.error||!reservation.data){this.error.set(reservation.error?this.auth.errorMessage(reservation.error):'Réservation introuvable ou déjà finalisée.');this.loading.set(false);return}const vehicle=await this.auth.supabase().from('vehicles').select('id,registration_number,make,model,rental_price,deposit_amount,status').eq('id',reservation.data.vehicle_id).single();if(vehicle.error){this.error.set(this.auth.errorMessage(vehicle.error));this.loading.set(false);return}this.reservation.set(reservation.data);this.vehicle.set(vehicle.data);this.form.set({departure_location:'',return_location:'',rental_price:vehicle.data.rental_price??0,deposit_amount:vehicle.data.deposit_amount??0,driving_zone:'',notes:reservation.data.observation??''});this.loading.set(false)}
  async save(){const value=this.form();if(Number(value.rental_price)<0||Number(value.deposit_amount)<0){this.error.set('Les montants doivent être positifs ou nuls.');return}this.saving.set(true);const result=await this.auth.supabase().rpc('create_rental_from_reservation',{target_reservation_id:this.reservationId,target_client_id:this.clientId,target_departure_location:value.departure_location||null,target_return_location:value.return_location||null,target_rental_price:Number(value.rental_price||0),target_deposit_amount:Number(value.deposit_amount||0),target_driving_zone:value.driving_zone||null,target_notes:value.notes||null});this.saving.set(false);if(result.error){this.error.set(this.auth.errorMessage(result.error));return}await this.router.navigate(['/rentals'])}
  back(){void this.router.navigate(['/reservation-client'],{queryParams:{reservation:this.reservationId}})}
}
