import { AfterViewInit, Component, ElementRef, OnDestroy, OnInit, ViewChild, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { Calendar } from '@fullcalendar/core';
import frLocale from '@fullcalendar/core/locales/fr';
import dayGridPlugin from '@fullcalendar/daygrid';
import timeGridPlugin from '@fullcalendar/timegrid';
import interactionPlugin from '@fullcalendar/interaction';
import { AuthService } from '../core/auth.service';

@Component({
  standalone: true,
  imports: [FormsModule, DatePipe],
  styles: [`.reservation-calendar{min-height:650px}.reservation-calendar .fc-event{white-space:normal;cursor:pointer}.dispatch-overlay{position:fixed;inset:0;z-index:1080;display:grid;place-items:center;padding:1rem;background:rgba(8,33,40,.62)}.dispatch-card{width:min(560px,100%);background:#fff;border-radius:20px;padding:1.5rem;box-shadow:0 22px 60px rgba(0,0,0,.25)}.recipient-list{max-height:170px;overflow:auto}.recipient-item{width:100%;text-align:left;margin-top:.4rem}@media(max-width:760px){.reservation-calendar{min-height:520px;font-size:.78rem}.reservation-calendar .fc-toolbar{flex-wrap:wrap;gap:.5rem}.reservation-calendar .fc-toolbar-title{font-size:1.05rem}.dispatch-card{padding:1.2rem;border-radius:16px}}`],
  template: `
    <div class="page-heading"><div><p class="eyebrow">PLANIFICATION</p><h1>Réservations</h1><p>Les réservations actives bloquent le véhicule jusqu’à leur finalisation ou annulation.</p></div>@if(auth.can('reservations','create')){<button class="btn btn-primary" (click)="openNew()">+ Nouvelle réservation</button>}</div>
    <div class="toolbar row g-2"><div class="col-md-5"><input class="form-control" [(ngModel)]="query" (input)="refresh()" placeholder="Nom, téléphone ou véhicule"></div><div class="col-md-4"><select class="form-select" [(ngModel)]="vehicleFilter" (change)="refresh()"><option value="">Tous les véhicules</option>@for(vehicle of vehicles();track vehicle.id){<option [value]="vehicle.id">{{vehicle.registration_number}} — {{vehicle.make}} {{vehicle.model}}</option>}</select></div><div class="col-md-3"><select class="form-select" [(ngModel)]="statusFilter" (change)="refresh()"><option value="active">Actives : en attente et validées</option><option value="pending">En attente</option><option value="validated">Validées</option><option value="finalized">Finalisées</option><option value="cancelled">Annulées</option><option value="">Tous les statuts</option></select></div></div>
    @if(error()){<div class="alert alert-danger">{{error()}}</div>}@if(message()){<div class="alert alert-success">{{message()}}</div>}
    @if(loading()){<div class="empty-state">Chargement des réservations…</div>}@else{@if(!visible().length){<div class="empty-state">Aucune réservation avec ces filtres.</div>}@else{<div class="table-responsive app-table"><table class="table align-middle mb-0"><thead><tr><th>Client</th><th>Véhicule</th><th>Période</th><th>Statut</th><th class="text-end">Actions</th></tr></thead><tbody>@for(item of visible();track item.id){<tr><td><strong>{{item.first_name}} {{item.last_name}}</strong><small class="d-block text-muted">{{item.phone}}</small></td><td>{{item.vehicles?.registration_number}}</td><td>{{item.planned_departure_date|date:'short'}}<small class="d-block text-muted">au {{item.planned_return_date|date:'short'}}</small></td><td><span class="badge text-bg-{{tone(item.status)}}">{{label(item)}}</span></td><td class="text-end"><button class="btn btn-sm btn-outline-primary me-1" (click)="show(item)">Voir</button>@if((item.status==='pending'||(item.status==='validated'&&!item.rental_id&&!item.client_contract_sent_at))&&auth.can('reservations','update')){@if(item.status==='pending'){<button class="btn btn-sm btn-success me-1" (click)="validate(item)">Valider</button>}@if(item.status==='validated'&&!item.rental_id&&!item.client_contract_sent_at){<button class="btn btn-sm btn-success me-1" (click)="finalize(item)">Finaliser</button>}<button class="btn btn-sm btn-outline-secondary me-1" (click)="openEdit(item)">Modifier</button><button class="btn btn-sm btn-outline-danger" (click)="cancel(item)">Annuler</button>}</td></tr>}</tbody></table></div>}}
    @if(form()){<section class="card form-card mt-4"><div class="card-body"><h2 class="h4">{{form()!.id?'Modifier':'Nouvelle'}} réservation</h2><p class="text-muted">Le statut est créé automatiquement à « En attente ».</p><div class="row g-3"><div class="col-md-4"><label>Prénom <span class="required">*</span></label><input class="form-control" [(ngModel)]="form()!.first_name"></div><div class="col-md-4"><label>Nom <span class="required">*</span></label><input class="form-control" [(ngModel)]="form()!.last_name"></div><div class="col-md-4"><label>Téléphone <span class="required">*</span></label><input class="form-control" [(ngModel)]="form()!.phone"></div><div class="col-md-6"><label>Véhicule <span class="required">*</span></label><select class="form-select" [(ngModel)]="form()!.vehicle_id"><option value="">Sélectionner un véhicule</option>@for(vehicle of vehicles();track vehicle.id){<option [value]="vehicle.id">{{vehicle.registration_number}} — {{vehicle.make}} {{vehicle.model}}</option>}</select></div><div class="col-md-3"><label>Départ prévu <span class="required">*</span></label><input class="form-control" type="datetime-local" [(ngModel)]="form()!.planned_departure_date"></div><div class="col-md-3"><label>Retour prévu <span class="required">*</span></label><input class="form-control" type="datetime-local" [(ngModel)]="form()!.planned_return_date"></div><div class="col-12"><label>Observation</label><textarea class="form-control" rows="3" [(ngModel)]="form()!.observation"></textarea></div></div><button class="btn btn-primary mt-3" [disabled]="saving()" (click)="save()">{{saving()?'Enregistrement…':'Enregistrer'}}</button><button class="btn btn-link mt-3" (click)="form.set(null)">Annuler</button></div></section>}
    @if(selected()){<section class="card form-card mt-4"><div class="card-body"><div class="d-flex justify-content-between"><div><h2 class="h4">Réservation {{label(selected()).toLowerCase()}}</h2><p class="mb-0">{{selected().first_name}} {{selected().last_name}} — {{selected().phone}}</p></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-secondary" (click)="selected.set(null)">Fermer</button><button class="btn-close" (click)="selected.set(null)"></button></div></div><dl class="row mt-3 mb-0"><dt class="col-sm-3">Véhicule</dt><dd class="col-sm-9">{{selected().vehicles?.registration_number}}</dd><dt class="col-sm-3">Période</dt><dd class="col-sm-9">{{selected().planned_departure_date|date:'medium'}} → {{selected().planned_return_date|date:'medium'}}</dd><dt class="col-sm-3">Observation</dt><dd class="col-sm-9">{{selected().observation||'—'}}</dd>@if(selected().status==='cancelled'){<dt class="col-sm-3">Annulation</dt><dd class="col-sm-9">{{selected().cancelled_at|date:'short'}} — {{selected().cancellation_reason||'Sans motif'}}</dd>}@if(selected().rental_id){<dt class="col-sm-3">Location créée</dt><dd class="col-sm-9">{{selected().rental_id}}</dd>}</dl></div></section>}
    @if(dispatch()){<div class="dispatch-overlay" role="dialog" aria-modal="true" aria-labelledby="dispatch-title"><section class="dispatch-card"><div class="d-flex justify-content-between gap-3"><div><p class="eyebrow mb-1">FINALISATION</p><h2 id="dispatch-title" class="h4 mb-2">Comment traiter cette réservation ?</h2></div><button class="btn-close" aria-label="Fermer" (click)="dispatch.set(null)"></button></div><p class="text-muted">{{dispatch().first_name}} {{dispatch().last_name}} a une réservation validée. Choisissez le parcours adapté.</p><div class="border rounded-3 p-3 mb-3"><h3 class="h6">Préparer côté Responsable</h3><p class="small text-muted mb-2">Le Responsable complète le client et la location comme aujourd’hui, puis finalise le dossier en interne.</p><button class="btn btn-outline-primary" (click)="prepareDispatch()">Préparer</button></div><div class="border rounded-3 p-3"><h3 class="h6">Envoyer au client</h3>@if(isOnlineReservation(dispatch())){<p class="small text-muted mb-2">Cette demande provient de l’espace client. Son compte est déjà associé : le contrat sera envoyé directement à {{dispatch().first_name}} {{dispatch().last_name}}.</p>}@else{<p class="small text-muted mb-2">Cette réservation a été créée en interne. Recherchez le compte client qui doit recevoir le contrat.</p><div class="input-group"><input class="form-control" [(ngModel)]="recipientQuery" (keyup.enter)="findRecipient()" placeholder="Nom, téléphone ou e-mail du client"><button class="btn btn-outline-secondary" type="button" (click)="findRecipient()">Rechercher</button></div>@if(recipients().length){<div class="recipient-list mt-2">@for(client of recipients();track client.id){<button class="btn btn-outline-primary recipient-item" type="button" (click)="chooseRecipient(client)"><strong>{{client.first_name}} {{client.last_name}}</strong> — {{client.phone}}<small class="d-block">{{client.email||'E-mail non renseigné'}}</small></button>}</div>}@if(selectedRecipient()){<p class="small text-success mt-2 mb-2"><strong>Destinataire :</strong> {{selectedRecipient().first_name}} {{selectedRecipient().last_name}} — {{selectedRecipient().phone}}</p>}}<button class="btn btn-primary" [disabled]="saving()" (click)="sendToClient()">{{saving()?'Envoi…':'Envoyer au client'}}</button></div></section></div>}
  `
})
export class ReservationsComponent implements OnInit, AfterViewInit, OnDestroy {
  @ViewChild('calendarHost') calendarHost?: ElementRef<HTMLElement>;
  calendar?: Calendar;
  rows = signal<any[]>([]); vehicles = signal<any[]>([]); form = signal<any>(null); selected = signal<any>(null); dispatch = signal<any>(null); recipients = signal<any[]>([]); selectedRecipient = signal<any>(null);
  loading = signal(false); saving = signal(false); error = signal(''); message = signal(''); query = ''; vehicleFilter = ''; statusFilter = ''; recipientQuery = '';
  constructor(public auth: AuthService, private router: Router) {}
  ngOnInit() { void this.load(); }
  ngAfterViewInit() { this.createCalendar(); }
  ngOnDestroy() { this.calendar?.destroy(); }
  async load() { this.loading.set(true); const [vehicles, reservations] = await Promise.all([this.auth.supabase().from('vehicles').select('id,registration_number,make,model').order('registration_number'), this.auth.supabase().from('reservations').select('*,vehicles(registration_number,make,model)').order('planned_departure_date', { ascending: false })]); this.loading.set(false); this.vehicles.set(vehicles.data ?? []); this.rows.set(reservations.data ?? []); this.error.set(vehicles.error ? this.auth.errorMessage(vehicles.error) : reservations.error ? this.auth.errorMessage(reservations.error) : ''); this.refresh(); }
  visible() { return this.filtered(true); }
  calendarItems() { return this.filtered(false); }
  filtered(withStatus: boolean) { const term = this.query.trim().toLowerCase(); return this.rows().filter(item => (!withStatus || !this.statusFilter || (this.statusFilter === 'active' ? ['pending', 'validated'].includes(item.status) : item.status === this.statusFilter)) && (!this.vehicleFilter || item.vehicle_id === this.vehicleFilter) && (!term || (item.first_name + ' ' + item.last_name + ' ' + item.phone + ' ' + (item.vehicles?.registration_number ?? '')).toLowerCase().includes(term))); }
  refresh() { if (!this.calendar) return; this.calendar.removeAllEvents(); this.calendar.addEventSource(this.calendarItems().map(item => ({ id: item.id, title: (item.vehicles?.registration_number ?? 'Véhicule') + ' · ' + item.first_name + ' ' + item.last_name + ' · ' + item.phone, start: item.planned_departure_date, end: item.planned_return_date, color: item.status === 'pending' ? '#d58b00' : item.status === 'validated' ? '#0b9cac' : item.status === 'finalized' ? '#198754' : '#6c757d', extendedProps: { reservation: item } }))); }
  createCalendar() { if (!this.calendarHost) return; this.calendar = new Calendar(this.calendarHost.nativeElement, { plugins: [dayGridPlugin, timeGridPlugin, interactionPlugin], initialView: 'dayGridMonth', locales: [frLocale], locale: 'fr', firstDay: 1, headerToolbar: { left: 'prev,next today', center: 'title', right: 'dayGridMonth,timeGridWeek,timeGridDay' }, buttonText: { today: 'Aujourd’hui', month: 'Mois', week: 'Semaine', day: 'Jour' }, height: 'auto', eventClick: info => this.show(info.event.extendedProps['reservation']) }); this.calendar.render(); this.refresh(); }
  openNew() { window.scrollTo({ top: 0, behavior: 'smooth' }); this.error.set(''); this.message.set(''); this.selected.set(null); this.form.set({ first_name: '', last_name: '', phone: '', vehicle_id: '', planned_departure_date: '', planned_return_date: '', observation: '' }); setTimeout(() => document.querySelector('.form-card')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0); }
  openEdit(item: any) { this.error.set(''); this.message.set(''); this.form.set({ ...item, planned_departure_date: this.local(item.planned_departure_date), planned_return_date: this.local(item.planned_return_date) }); }
  local(value: string) { return value ? new Date(value).toISOString().slice(0, 16) : ''; }
  async save() { const value = this.form(); if (!value?.first_name?.trim() || !value?.last_name?.trim() || !value?.phone?.trim() || !value?.vehicle_id || !value?.planned_departure_date || !value?.planned_return_date) { this.error.set('Prénom, nom, téléphone, véhicule et période sont obligatoires.'); return; } this.saving.set(true); const payload = { first_name: value.first_name.trim(), last_name: value.last_name.trim(), phone: value.phone.trim(), vehicle_id: value.vehicle_id, planned_departure_date: new Date(value.planned_departure_date).toISOString(), planned_return_date: new Date(value.planned_return_date).toISOString(), observation: value.observation || null }; const result = value.id ? await this.auth.supabase().from('reservations').update(payload).eq('id', value.id) : await this.auth.supabase().from('reservations').insert(payload); this.saving.set(false); if (result.error) { this.error.set(this.auth.errorMessage(result.error)); return; } this.form.set(null); this.message.set('Réservation enregistrée.'); await this.load(); }
  show(item: any) { this.selected.set(item); setTimeout(() => document.querySelector('.form-card')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 0); }
  async validate(item: any) { const result = await this.auth.supabase().rpc('validate_reservation', { target_reservation_id: item.id }); if (result.error) { this.error.set(this.auth.errorMessage(result.error)); return; } this.message.set('Réservation validée. Elle reste bloquante jusqu’à sa finalisation ou son annulation.'); await this.load(); }
  finalize(item: any) { this.error.set(''); this.message.set(''); this.recipients.set([]); this.selectedRecipient.set(null); this.recipientQuery = ''; this.dispatch.set(item); }
  prepareDispatch() { const item = this.dispatch(); this.dispatch.set(null); if (item) void this.router.navigate(['/reservation-client'], { queryParams: { reservation: item.id } }); }
  async findRecipient() { const term = this.recipientQuery.trim(); if (!term) { this.recipients.set([]); return; } const escaped = term.replace(/[,%()]/g, ''); const result = await this.auth.supabase().from('clients').select('id,profile_id,first_name,last_name,phone,email').not('profile_id', 'is', null).or(`first_name.ilike.%${escaped}%,last_name.ilike.%${escaped}%,phone.ilike.%${escaped}%,email.ilike.%${escaped}%`).order('last_name').limit(12); if (result.error) { this.error.set(this.auth.errorMessage(result.error)); return; } this.recipients.set(result.data ?? []); }
  chooseRecipient(client: any) { this.selectedRecipient.set(client); this.recipients.set([]); this.recipientQuery = `${client.first_name} ${client.last_name} — ${client.phone}`; }
  isOnlineReservation(item: any) { return !!item?.client_profile_id; }
  async sendToClient() { const item = this.dispatch(), recipient = this.selectedRecipient(); if (!item) return; if (!this.isOnlineReservation(item) && !recipient?.profile_id) { this.error.set('Recherchez et sélectionnez le compte client qui doit recevoir le contrat.'); return; } this.saving.set(true); this.error.set(''); const result = this.isOnlineReservation(item) ? await this.auth.supabase().rpc('send_reservation_to_client', { target_reservation_id: item.id }) : await this.auth.supabase().rpc('send_reservation_to_selected_client', { target_reservation_id: item.id, target_client_profile_id: recipient.profile_id }); this.saving.set(false); if (result.error) { this.error.set(this.auth.errorMessage(result.error)); return; } this.dispatch.set(null); this.message.set('Location et contrat préparés. La location est maintenant visible dans Locations : ouvrez sa fiche pour confirmer « Paiement reçu » après l’encaissement réel.'); await this.load(); }
  async cancel(item: any) { if (!confirm('Annuler la réservation de ' + item.first_name + ' ' + item.last_name + ' ?')) return; const reason = prompt('Motif d’annulation (facultatif)') ?? ''; const result = await this.auth.supabase().rpc('cancel_reservation', { target_reservation_id: item.id, reason }); if (result.error) { this.error.set(this.auth.errorMessage(result.error)); return; } this.message.set('Réservation annulée. Le véhicule est immédiatement libéré.'); this.selected.set(null); await this.load(); }
  label(item: any) { if (item.status === 'validated' && item.rental_id) return 'Contrat en attente de signatures'; if (item.status === 'validated' && item.client_contract_sent_at) return 'Dossier envoyé au client'; return ({ pending: 'En attente', validated: 'Validée', finalized: 'Finalisée', cancelled: 'Annulée' } as Record<string, string>)[item.status] ?? item.status; }
  tone(status: string) { return ({ pending: 'warning', validated: 'info', finalized: 'success', cancelled: 'secondary' } as Record<string, string>)[status] ?? 'secondary'; }
}
