import { Component, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../core/auth.service';

@Component({
  standalone: true,
  imports: [FormsModule, RouterLink],
  styles: [`
    .upload-zone{padding:1rem;border:1px dashed #b9d0d5;border-radius:14px;background:#f8fbfb}.upload-zone label{display:block;font-weight:750}.upload-zone small{display:block;margin:.2rem 0 .65rem;color:#667f85}.photo-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:.75rem}.photo-item{position:relative;display:block;height:92px;border-radius:10px;overflow:hidden;border:1px solid #d9e6e8;background:#eff5f6}.photo-item img{width:100%;height:100%;object-fit:cover}.photo-item span{position:absolute;inset:auto 0 0;padding:.25rem .35rem;background:rgba(7,34,41,.68);color:#fff;font-size:.68rem;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.document-list{display:flex;flex-wrap:wrap;gap:.5rem}.document-list .badge{max-width:100%;overflow:hidden;text-overflow:ellipsis}
  `],
  template: `
<div class="page-heading"><div><p class="eyebrow">PARC AUTOMOBILE</p><h1>Véhicules</h1><p>Gérez le parc, les échéances, les documents et les photos destinées au portail client.</p></div>@if(auth.can('vehicles','create')){<button class="btn btn-primary" (click)="newVehicle()">+ Nouveau véhicule</button>}</div>
<div class="toolbar"><input class="form-control" [(ngModel)]="query" placeholder="Immatriculation, marque ou modèle" (input)="load()"></div>
@if(error()){<div class="alert alert-danger">{{error()}}</div>}@if(message()){<div class="alert alert-success">{{message()}}</div>}@if(loading()){<div class="empty-state">Chargement des véhicules…</div>}@else if(!rows().length){<div class="empty-state">Aucun véhicule ne correspond à votre recherche.</div>}@else{<div class="table-responsive app-table"><table class="table align-middle mb-0"><thead><tr><th>Véhicule</th><th>Immatriculation</th><th>Statut</th><th>Échéances</th><th class="text-end">Action</th></tr></thead><tbody>@for(v of rows();track v.id){<tr><td><strong>{{v.make}} {{v.model}}</strong><small class="d-block text-muted">{{v.category||'Catégorie non renseignée'}}</small></td><td>{{v.registration_number}}</td><td><span class="badge text-bg-{{statusTone(v.status)}}">{{statusLabel(v.status)}}</span></td><td><small>Assurance : {{v.insurance_expiry_date||'—'}}<br>Contrôle : {{v.technical_inspection_expiry_date||'—'}}</small></td><td class="text-end"><button class="btn btn-sm btn-outline-primary" (click)="open(v)">Fiche</button></td></tr>}</tbody></table></div>}
@if(editing()){<section class="card form-card mt-4"><div class="card-body"><div class="d-flex justify-content-between align-items-start mb-3"><div><h2 class="h4 mb-1">{{editing()!.id?'Fiche véhicule':'Nouveau véhicule'}}</h2><p class="text-muted mb-0">Les disponibilités restent contrôlées par PostgreSQL.</p></div><div class="d-flex gap-2"><button class="btn btn-sm btn-outline-secondary" (click)="close()">Fermer</button><button class="btn-close" (click)="close()" aria-label="Fermer"></button></div></div><div class="row g-3"><div class="col-md-4"><label>Immatriculation <span class="required">*</span></label><input class="form-control" [(ngModel)]="editing()!.registration_number"></div><div class="col-md-4"><label>Marque <span class="required">*</span></label><input class="form-control" [(ngModel)]="editing()!.make"></div><div class="col-md-4"><label>Modèle <span class="required">*</span></label><input class="form-control" [(ngModel)]="editing()!.model"></div><div class="col-md-3"><label>Couleur</label><input class="form-control" [(ngModel)]="editing()!.color"></div><div class="col-md-3"><label>Année</label><input class="form-control" type="number" [(ngModel)]="editing()!.year"></div><div class="col-md-3"><label>Kilométrage</label><input class="form-control" type="number" min="0" [(ngModel)]="editing()!.mileage"></div><div class="col-md-3"><label>Statut</label><select class="form-select" [(ngModel)]="editing()!.status"><option value="available">Disponible</option><option value="on_rental">En location</option><option value="maintenance">Maintenance</option><option value="unavailable">Indisponible</option></select></div><div class="col-md-4"><label>Carburant</label><input class="form-control" [(ngModel)]="editing()!.fuel_type"></div><div class="col-md-4"><label>Transmission</label><input class="form-control" [(ngModel)]="editing()!.transmission"></div><div class="col-md-4"><label>Catégorie</label><input class="form-control" [(ngModel)]="editing()!.category"></div><div class="col-md-3"><label>Prix / jour</label><input class="form-control" type="number" min="0" [(ngModel)]="editing()!.rental_price"></div><div class="col-md-3"><label>Caution</label><input class="form-control" type="number" min="0" [(ngModel)]="editing()!.deposit_amount"></div><div class="col-md-3"><label>Expiration assurance</label><input class="form-control" type="date" [(ngModel)]="editing()!.insurance_expiry_date"></div><div class="col-md-3"><label>Expiration contrôle technique</label><input class="form-control" type="date" [(ngModel)]="editing()!.technical_inspection_expiry_date"></div></div>
@if(editing()!.id){<hr><div class="row g-3"><div class="col-lg-5"><div class="upload-zone h-100"><label>Documents du véhicule</label><small>Carte grise, assurance, facture ou autre justificatif. Plusieurs fichiers peuvent être sélectionnés.</small><input class="form-control" type="file" multiple (change)="uploadFiles($event,'document')"><div class="document-list mt-3">@for(d of documents();track d.id){<a class="badge text-bg-light border text-decoration-none" href="#" (click)="download(d,$event)">{{d.document_name}}</a>}@empty{<small class="text-muted">Aucun document ajouté.</small>}</div></div></div><div class="col-lg-7"><div class="upload-zone h-100"><label>Photos du véhicule</label><small>Ajoutez une ou plusieurs photos. Elles seront affichées automatiquement dans la galerie du portail client.</small><input class="form-control" type="file" accept="image/*" multiple (change)="uploadFiles($event,'photo')"><div class="photo-grid mt-3">@for(photo of photos();track photo.id){<a class="photo-item" href="#" (click)="download(photo,$event)" title="Ouvrir {{photo.document_name}}"><img [src]="photo.url" alt="{{photo.document_name}}"><span>{{photo.document_name}}</span></a>}@empty{<small class="text-muted">Aucune photo ajoutée.</small>}</div></div></div></div><div class="mt-3 d-flex flex-wrap gap-2">@if(auth.can('maintenance')){<a class="btn btn-outline-primary" [routerLink]="['/maintenance']" [queryParams]="{vehicle:editing()!.id}">Maintenance</a>}@if(auth.can('incidents')){<a class="btn btn-outline-warning" [routerLink]="['/incidents']" [queryParams]="{vehicle:editing()!.id}">Incidents</a>}</div>}
<div class="mt-4 d-flex flex-wrap gap-2">@if(auth.can('vehicles',editing()!.id?'update':'create')){<button class="btn btn-primary" [disabled]="saving()" (click)="save()">{{saving()?'Enregistrement…':'Enregistrer les informations'}}</button>}@if(editing()!.id&&auth.can('vehicles','delete')){<button class="btn btn-outline-danger" [disabled]="saving()" (click)="remove()">Retirer ce véhicule</button>}</div></div></section>}
`})
export class VehiclesComponent implements OnInit {
  rows=signal<any[]>([]); editing=signal<any>(null); documents=signal<any[]>([]); photos=signal<any[]>([]); error=signal(''); message=signal(''); loading=signal(false); saving=signal(false); query='';
  constructor(public auth:AuthService){}
  ngOnInit(){this.load()}
  private clear(){this.error.set('');this.message.set('')}
  async load(){this.loading.set(true);this.clear();let q=this.auth.supabase().from('vehicles').select('*').order('created_at',{ascending:false});if(this.query.trim())q=q.or('registration_number.ilike.%'+this.query.trim()+'%,make.ilike.%'+this.query.trim()+'%,model.ilike.%'+this.query.trim()+'%');const r=await q;this.rows.set(r.data??[]);if(r.error)this.error.set(this.auth.errorMessage(r.error));this.loading.set(false)}
  newVehicle(){this.clear();this.editing.set({status:'available',mileage:0,rental_price:0,deposit_amount:0});this.documents.set([]);this.photos.set([])}
  close(){this.editing.set(null);this.documents.set([]);this.photos.set([])}
  async open(v:any){this.clear();this.editing.set({...v});const r=await this.auth.supabase().from('vehicle_documents').select('*').eq('vehicle_id',v.id).order('created_at',{ascending:false});if(r.error){this.error.set(this.auth.errorMessage(r.error));return}const files=r.data??[];const pictures=files.filter((d:any)=>d.document_type==='photo'||String(d.mime_type??'').startsWith('image/'));this.documents.set(files.filter((d:any)=>!pictures.includes(d)));const withUrls=await Promise.all(pictures.map(async(d:any)=>{const url=await this.auth.supabase().storage.from('rental-documents').createSignedUrl(d.storage_path,600);return{...d,url:url.data?.signedUrl??''}}));this.photos.set(withUrls)}
  async save(){this.clear();const v=this.editing();if(!v?.registration_number?.trim()||!v?.make?.trim()||!v?.model?.trim()){this.error.set('Immatriculation, marque et modèle sont obligatoires.');return}this.saving.set(true);const r=v.id?await this.auth.supabase().from('vehicles').update(v).eq('id',v.id).select().single():await this.auth.supabase().from('vehicles').insert(v).select().single();this.saving.set(false);if(r.error){this.error.set(this.auth.errorMessage(r.error));return}this.message.set(v.id?'Informations du véhicule mises à jour.':'Véhicule ajouté. Ajoutez ensuite ses documents ou photos depuis sa fiche.');if(r.data)await this.open(r.data);await this.load()}
  async remove(){const v=this.editing();if(!v?.id)return;if(!window.confirm('Retirer définitivement ce véhicule ? Cette action est impossible si le véhicule est lié à une location, une réservation, une inspection ou un historique.'))return;this.clear();this.saving.set(true);const files=await this.auth.supabase().from('vehicle_documents').select('storage_path').eq('vehicle_id',v.id);const r=await this.auth.supabase().from('vehicles').delete().eq('id',v.id);this.saving.set(false);if(r.error){this.error.set(this.auth.errorMessage(r.error));return}const paths=(files.data??[]).map((d:any)=>d.storage_path);if(paths.length){const cleanup=await this.auth.supabase().storage.from('rental-documents').remove(paths);if(cleanup.error)this.message.set('Véhicule retiré. Certains fichiers associés devront être supprimés depuis Storage.')}this.close();this.message.set(this.message()||'Véhicule retiré définitivement.');await this.load()}
  async uploadFiles(event:Event,type:'document'|'photo'){const v=this.editing();const files=Array.from((event.target as HTMLInputElement).files??[]);if(!v?.id||!files.length)return;this.clear();if(type==='photo'&&files.some(file=>!file.type.startsWith('image/'))){this.error.set('La zone Photos accepte uniquement des images.');return}this.saving.set(true);let count=0;for(const file of files){const path='vehicles/'+v.id+'/'+crypto.randomUUID()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'_');const up=await this.auth.supabase().storage.from('rental-documents').upload(path,file,{contentType:file.type});if(up.error){this.error.set(this.auth.errorMessage(up.error));continue}const saved=await this.auth.supabase().from('vehicle_documents').insert({vehicle_id:v.id,document_type:type,document_name:file.name,storage_path:path,mime_type:file.type,file_size:file.size});if(saved.error)this.error.set(this.auth.errorMessage(saved.error));else count++}this.saving.set(false);(event.target as HTMLInputElement).value='';if(count)this.message.set(count+' fichier'+(count>1?'s ajoutés.':' ajouté.'));await this.open(v)}
  async download(d:any,event:Event){event.preventDefault();const r=await this.auth.supabase().storage.from('rental-documents').createSignedUrl(d.storage_path,60);if(r.error)this.error.set(this.auth.errorMessage(r.error));else window.open(r.data.signedUrl,'_blank','noopener')}
  statusTone(s:string){return({available:'success',on_rental:'primary',maintenance:'warning',unavailable:'secondary'}as Record<string,string>)[s]??'secondary'}
  statusLabel(s:string){return({available:'Disponible',on_rental:'En location',maintenance:'Maintenance',unavailable:'Indisponible'}as Record<string,string>)[s]??s}
}
